### ISSUE TITLE
Use COLLATE NOCASE by default for SQLite

### ISSUE THREAD

**Issue by sebastienros** [sebastienros/yessql#121]
Text queries are case sensitive by default. Add it the creation scripts, include the index as they need to match.

**Comment by hishamco** [comment]
As `NOCASE` is a collation for case-insensitive comparing. But it doesn’t support Unicode only ASCII

**Comment by hishamco** [comment]
FYI we can use `COLLATE NOCASE` in the column creation

**Comment by sebastienros** [comment]
@hishamco yes, this is what I had in mind. It will require to add some test for case insensitive matches, and also for unicode chars which I think we don't have yet.

**Comment by hishamco** [comment]
Hope to get on this soon
