### ISSUE TITLE
How to determine if the database has already been initialized?

### ISSUE THREAD

**Issue by pmarflee** [sebastienros/yessql#131]
Calling `InitializeAsync()` when the database has already been initialized throws an error, saying that the 'Document' table already exists.  How to determine then if the database has already been initialized?

I see from the source that OrchardCore works around this by placing the call in a `try...catch` block.  Is there a better way to handle it than this?

**Comment by hishamco** [comment]
Simply you can check the `Document` table existence. @sebastienros is there a better way to check if the database is already initialized?

**Comment by sebastienros** [comment]
I could suggest we check for the table automatically when calling `InitializeAsync`. How does EF do?

**Comment by pmarflee** [comment]
For now, I am running some SQL queries in my application startup class to check whether the Document and any Index tables have already been created: 

https://github.com/pmarflee/sphinx-adventure/blob/master/SphinxAdventure.Api/Startup.cs

While this serves as a workaround, having to drop back into SQL to do these checks is not ideal.  It would be good if the library provided a way to do these checks.

**Comment by sebastienros** [comment]
I think it should just try to detect the Document table and no-op in this case. Probably by add a method that returns the statement in dialects. The method would take a table name as parameter. Then do the same thing for `InitializeCollectionAsync`.

**Comment by CoskunSunali** [comment]
I was just trying to solve this by myself and it seems that you already have an issue. Great!

**Comment by sebastienros** [comment]
Fixed by #154
