### ISSUE TITLE
OFFSET and LIMIT fail is Order By is not included

### ISSUE THREAD

**Issue by bruxite** [sebastienros/yessql#137]
It appears that SQL requires an Order By statement to support OFFSET and LIMIT. YESSQL does not enforce this case, instead it throws an error message all the way to the client.

Error message
An error occured while executing the SQL query: Incorrect syntax near 'OFFSET'.
 Invalid usage of the option NEXT in the FETCH statement.

Reference
https://technet.microsoft.com/en-us/library/gg699618(v=sql.110).aspx

"ORDER BY is mandatory to use OFFSET and FETCH clause."

**Comment by DaveEmmerson** [comment]
@bruxite @sebastienros I think this can be closed due https://github.com/sebastienros/yessql/pull/91?

**Comment by sebastienros** [comment]
Thanks @DaveEmmerson  for looking into that
