### ISSUE TITLE
Int64 document identifiers

### ISSUE THREAD

**Issue by CoskunSunali** [sebastienros/yessql#142]
What would it take to be able to create the Document table with a primary key of `Int64` value (bigint)?

That is for products expected to have more than 2.1 billion documents (including those deleted) which is not unlikely.

**Comment by sebastienros** [comment]
I assume we should just change all the code to use this ... Do you know it it's supported in all dbs and the impact on perf it would have? I'd like to know if it would be necessary to support both.

**Comment by CoskunSunali** [comment]
As far as I know, all providers that YesSql support so far (mysql, sql server, postgresql and sqlite) support `bigint` column type.

Event though I don't have real life benchmarks, I am almost certain that the performance will be effected negatively in a scale of some milliseconds. The storage size will increase after all, indexes will be bigger, disk IO will probably cost more time to process.

However, we shall not forget that the performance lose doesn't matter as soon as the int32 primary keys start overflowing and break the application.

There are some disk size comparisons for MySQL at http://ronaldbradford.com/blog/bigint-v-int-is-there-a-big-deal-2008-07-18/

These guys find similar results for int/bigint on PostgreSQL at https://stackoverflow.com/questions/38053596/benchmark-bigint-vs-int-on-postgresql

There is a very details comparison for MSSQL at https://www.mssqltips.com/sqlservertip/5115/compare-sql-server-table-join-performance-for-int-vs-bigint-vs-guid-data-types/

I don't have any links for SQLite but as far as I know SQLite automatically decides whether it should use int or bigint based on the magnitude of the value.

**Comment by IanYates** [comment]
Related PR here
https://github.com/sebastienros/yessql/pull/123

**Comment by sebastienros** [comment]
@IanYates I knew there was something like this, couldn't find it in the issues ;) Thanks

**Comment by CoskunSunali** [comment]
Thanks @IanYates. It seems that there is some more work to do there. E.g. index tables should have `long` identifiers as well as several methods should accept long instead of int too. @sebastienros already mentions them [here](https://github.com/sebastienros/yessql/pull/123#issuecomment-422435816).

Do you think you can complete it any time soon?

I know it is easy to change the things when you want to support either int or long but gets complicated when you want to support both.

**Comment by sebastienros** [comment]
Taking another look at the PR, I see two different features are requested.
- the fact that CreateColumn should allow to create identity columns that are bigint
- have all Document and Index table use bigint by default (even if the classes use int only)

The PR implements the first case. The current issue asks for the second.

In that case I assume the PR is fine, but it looks useless to me as it's not used by the document and index tables which are hard-coded with `int`.

It looks like we could just add a property in the `SchemaBuilder` to use BigInt or not, and then use this switch to generate the correct SQL. And this would be used everywhere Identity columns need to be created. And the switch would be based on the `Int64` type in the `Command.DbType` like in the PR.

**Comment by CoskunSunali** [comment]
@sebastienros The idea with `SchemaBuilder` accepting a property sounds great but how about the API itself? I mean, methods and constructors that accept `int` or `int[]` or `IEnumerable<int>`? Having overloads between `int` and `long` usually sucks. The compiler cannot automatically interpret whether you meant to use `int` or `long` when you have the following.

```cs
void Foo(int bar);
void Foo(long bar);

Foo(123); // 123 is int or long?
```

For example: https://github.com/sebastienros/yessql/blob/dev/src/YesSql.Core/Commands/CreateIndexCommand.cs#L21

https://github.com/sebastienros/yessql/blob/dev/src/YesSql.Core/Store.cs#L37

https://github.com/sebastienros/yessql/blob/dev/src/YesSql.Core/Store.cs#L188

**Comment by sebastienros** [comment]
@CoskunSunali we can have two dictionaries, or make the `Store` class generic. Or have two concrete store classes. or use long everywhere, and cast `int` to `long` when necessary.

**Comment by CoskunSunali** [comment]
@IanYates Oh, sorry! My bad and thanks for contributing to the issue then :)

@sebastienros Just trying to brainstorm. I believe making the `Store` class generic won't solve the issue because of the commands having reference to `int`. They will have to be made generic too, which means lots of work and new tests, probably. Two dictionaries is an approach but again won't solve the issue because of the problem I just mentioned (commands, etc). Two concrete store classes either, unless commands are generic.

Using `long` everywhere is the easiest of all, actually, I just cloned the project and made everything long in about 5 minutes and it just works. And one advantage of having it `long` everywhere is that you don't actually have to cast `int` to `long` anywhere since `int` is compatible with `long` out of the box.

You being the owner of the project, I guess it is your call but however I might help or contribute, just ask :)

Thanks for your attention.

**Comment by sebastienros** [comment]
If long everywhere works, then let's do it. And does it work if you don't change the domain classes that have `int` Ids ? I assume if you don't have to change the domain classes in the tests, it's perfect.

**Comment by CoskunSunali** [comment]
Unfortunately the domain classes have to be changed. They won't work having ids of type `int` due to the [DefaultIdentifierFactory L32](https://github.com/sebastienros/yessql/blob/dev/src/YesSql.Core/Data/DefaultIdentifierFactory.cs#L32) where `IdAccessor<TEntity, int>` cannot be casted to `IIdAccessor<long>` and returns `null` because `IdAccessor<TEntity, int>` actually implements `IIdAccessor<int>`. So `IIdAccessor<int>` cannot be casted to `IIdAccessor<long>` :(

Implicit casting from `int` to `long` is supported but not the other way around.

I can see two options. The identifier type should be checked prior to calling `store.GetIdAccessor` and two separate `GetIdAccessor` methods should be implemented, one for `int` and another for `long`, just like you mentioned earlier. However, this approach requires doing this everywhere we access the `IIdAccessor` so the correct one is returned all the time. All calls to `GetIdAccessor` are made in the `store` class and there are 6 of them in total.

Other option is forcing people to change the domain classes to have `long` identifiers but I don't know how realistic is that.

The same problem exists even if you decide to allow developers to decide what kind of an identifier they are using. No one can have some ids as `int` and some others as `long` unless the library decides what type of an id the entity has and get the appropriate `IIdAccessor` before calling `GetIdAccessor` with the correct type.

**Comment by sebastienros** [comment]
I think we can have a single internal dictionary using `'long`, but do two lookups. It's cached so it's fine. When using `int` we'll do a cast in the delegate.

**Comment by CoskunSunali** [comment]
> When using int we'll do a cast in the delegate.

Can you describe what you mean? I am currently working on integrating YesSql into my product so I can give it a try.

**Comment by sebastienros** [comment]
Change `IIdAccessor<long>` to `IIdAccessor<int>`, then adapt the code to fill this list with correct code. At some point you need to read `Id` properties that can be either `int` or `long` but the accessor will always manipulate longs in the API, but do explicit conversions if necessary.

**Comment by CoskunSunali** [comment]
Alright, how about the following lambda expressions? I will go ahead and make a PR if you confirm.

By the way, this thing will break as soon as the ids overflow and cannot be casted from `long` to `int` but I guess that is expected anyway, people know their application will break if they keep using `int` and have overflowing numbers.

```cs
// getter:

.Lambda #Lambda1<System.Func`2[MyApp.Entity,System.Int64]>(MyApp.Entity $entity) {
    (System.Int64)$entity.Id
}

// setter:

.Lambda #Lambda1<System.Action`2[MyApp.Entity,System.Int64]>(MyApp.Entity $entity, System.Int64 $id) {
    $entity.Id = (System.Int32)$id
}
```

I tested saving a new document, updating a document and querying documents and they all seem to work.

**Comment by CoskunSunali** [comment]
By the way, using the expressions I shared in my previous comment, we are not obliged to have `IIdAccessor<int>`. Just one `IIdAccessor<long>` will be enough. `long` will be used **everywhere**. It will just fallback to this custom expression whenever a domain entity has its identifier as `int` instead of the expected `long`.

```cs
// T: long (what we expect)
// tProperty: int (what the entity has)

if (typeof(T) != tProperty && typeof(T) == typeof(long) && tProperty == typeof(int))
```

**Comment by sebastienros** [comment]
That's what I meant

> Change IIdAccessor<long> to IIdAccessor<int>

Apparently I inverted the two

**Comment by CoskunSunali** [comment]
Okay, finally, how about existing projects using YesSql?

As soon as they update to the new version of YesSql, they will have the `Document` table with `int` identifier and index tables with `int` foreign key relations to the `Document` table.

This is not going to break the applications, just tested but they will not be migrated to take advantage of `long` identifiers either.

How would you like to proceed?

**Comment by CoskunSunali** [comment]
I said last question but came across [this article](http://www.sqlitetutorial.net/sqlite-primary-key/) which states the following. What do you think? Shall I continue with "long identifiers all the way" change?

> When you create a table without specifying the WITHOUT ROWID option, SQLite adds an implicit column called rowid that stores 64-bit signed integer. The rowid column is a key that uniquely identifies the row within its table. The table that has rowid column is called rowid table.
> 
> If a table has the primary key that consists of one column, and that column defined as INTEGER, exactly INTEGER in any cases, such as,INTEGER,integer, etc., then this primary key column becomes an alias for the rowid column.
> 
> Notice that if you assign another integer type such as: BIGINT, UNSIGNED INT, etc., to the primary key column, this column is not the alias for the rowid column.
> 
> Because the rowid table stores data as a B-Tree, querying and sorting data using rowid are very fast. It is faster than using a primary key that is not an alias of the rowid.
> 
> Another important note is that if you declare a column with the INTEGER type and PRIMARY KEY DESC clause, it does not become an alias for the rowid column.

Do we care about the ROWID?

**Comment by sebastienros** [comment]
would be hard to handle, we use LOHI to generate an id server side, so we know the id before we actually create the document

**Comment by CoskunSunali** [comment]
Which means? What I understand is that SQLite uses 8 byte values for `INTEGER` columns since version 3 and `INTEGER` primary keys are an alias to ROWID which is `always` 64 bits.

Shall I just leave the SQLite dialect using `integer primary key autoincrement` and continue with the rest of the PR?

Also, `dev` or `master`? Which one do you prefer me to point my PR to?

**Comment by sebastienros** [comment]
dev for PRs

Oh, if there are some `integer primary key autoincrement` (not using LOHI) then we can use this ROWID instead. Whatever is better and doesn't break the unit test is a GO !

**Comment by sebastienros** [comment]
@CoskunSunali totally unrelated, have you looked at Orchard Core, I assume you would love how what it provides (multi-tenancy and modularity framework).

**Comment by iamdroppy** [comment]
In all honesty, I don't think Primary Keys should be auto incremental at all, or at least there should be an option to change that.

A few points of interest:
* generating the PK without having to make a round-trip to the database to fetch the PK (can be used for bulk insert of data when you need to PK later for some other queries, like to add it as a FK to another table)
* easier management when you have a cluster, and easier to merge tables, since they're "universally unique"
* 128-bit value

Downsides:
* no order of when the data has been added

**Comment by sebastienros** [comment]
@iamdroppy  The id is not used, there is another value (DocumentId) that is used like you are describing, and this one is using the HI-LO algorithm, so this is generated by the client.
