### ISSUE TITLE
Signed Assemblies?

### ISSUE THREAD

**Issue by wedge206** [sebastienros/yessql#175]
Some build/deploy systems require assemblies and their dependencies to be signed and require a strong name.
Can we add a Strong Name to each of the Yessql assemblies?

**Comment by sebastienros** [comment]
Yes. Do you want to create a PR?

**Comment by wedge206** [comment]
Sure.
I'll probably do secondary signed projects, instead of signing the existing projects.  Similar to how Dapper does it.  That way the signed yessql projects can reference the signed Dapper packages.  This way there is no need to change references on the existing projects.

**Comment by hishamco** [comment]
This should be closed
