### ISSUE TITLE
ReIndexing can fail when using custom type names

### ISSUE THREAD

**Issue by wedge206** [sebastienros/yessql#183]
When using custom type names and attempting to reindex the db in a manner like this:

`var entityList = await session.Query().Any().ListAsync();
foreach (var entity in entityList)
{
    session.Save(entity);
}`

The re-index does not work, because all objects are retrieved as JsonObjects, and then its unable to map the type to its indexproviders.  Seems like the fix will have to be around how the IContentSerializer is called.
I'll work on a fix, but its low-pri for now since there is a decent workaround

Workaround:
Retrieve documents explicitly by type.  eg:
`var entityList = await session.Query<T>().ListAsync();
foreach (var entity in entityList)
{
    session.Save(entity);
}`

**Comment by sebastienros** [comment]
There is a unit test that ensure `Any()` resolves the correct type. And I just tried this new one:

```
[Fact]
        public async Task ShouldResolveManyTypes()
        {
            using (var session = _store.CreateSession())
            {
                var bill = new Person
                {
                    Firstname = "Bill",
                    Lastname = "Gates"
                };

                var lion = new Animal
                {
                    Name = "Lion"
                };

                session.Save(bill);
                session.Save(lion);
            }

            using (var session = _store.CreateSession())
            {
                var all = await session.Query().Any().ListAsync();

                Assert.Equal(2, all.Count());
                Assert.Contains(all, x => x is Person);
                Assert.Contains(all, x => x is Animal);
            }
        }
```

**Comment by wedge206** [comment]
The test probably isn’t testing using a custom type name.  That test will need to be added too.

**Comment by sebastienros** [comment]
I can see a difference with you code, I will try to call `Save`. However if the code you shared `Save()` would be no-op because nothing would have changed. We might need a custom overload to force it, in case you want the indices to be computed again.

**Comment by wedge206** [comment]
If you add this in the CreateTables():
`_store.TypeNames[typeof(Person)] = "People";`

Then the ShouldResolveManyTypes() test fails.

**Comment by sebastienros** [comment]
"ReIndexing can fail when using __custom type names__"

Now I understand what you mean

**Comment by wedge206** [comment]
I think I have a fix, updating the TypeService.  It requires a reverse lookup from the name to the type.
