### ISSUE TITLE
Make Store constructor public

### ISSUE THREAD

**Issue by sfmskywalker** [sebastienros/yessql#188]
I would like to asynchronously initialize the `Store` instead of doing it using a blocking call from the service registration step (using [asynchronous initialization](https://thomaslevesque.com/2018/09/25/asynchronous-initialization-in-asp-net-core-revisited/)).

Unfortunately, the only way to to construct a `Store` is through `StoreFactory`.

What I'd like to do is:

1. Register `Store` as a singleton (uninitialized)
2. Use async initialization to initialize the store (which will happen before the app starts, so it's all good)

If you agree I'll send a PR.

**Comment by sfmskywalker** [comment]
Actually, I like this approach even more: https://andrewlock.net/running-async-tasks-on-app-startup-in-asp-net-core-part-2/ - it doesn't require changing `Program.cs`, which means a library could run async tasks before Kestrel starts:

![](https://andrewlock.net/content/images/p/banner_18.png)

**Comment by sebastienros** [comment]
I don't understand what you need to change in yessql to do that?

**Comment by sfmskywalker** [comment]
Sorry, I wasn't being very clear.

What I want to do is register `Store` as a singleton without having to do `.GetAwaiter().GetResult()`. For example, [Orchard Core does this](https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.Data/OrchardCoreBuilderExtensions.cs#L89):

```csharp
...
var store = StoreFactory.CreateAsync(storeConfiguration).GetAwaiter().GetResult();
...
return store;
```

Not saying that it's bad the way it is: this happens in the startup thread anyway so no issued with deadlocks. But I thought it'd be interesting to see if I could register a `Store` singleton without having to initialize it during service registration, but instead perform initialization asynchronously after the service container has been built. 

Basically just doing this:

```csharp
return new Store(); // <-- won't compile because constructor is internal
```

And then in my async startup task do this:

```csharp
public class StoreInitializationTask : IStartupTask
{
    private readonly IStore _store;
    private readonly IEnumerable<IIndexProvider> _indexProviders;

    public StoreInitializationTask(IStore store, IEnumerable<IIndexProvider> indexProviders)
    {
        _store = store;
        _indexProviders = indexProviders;
    }
    
    public async Task ExecuteAsync(CancellationToken cancellationToken = default)
    {
        await _store.InitializeAsync(); // This won't compile because InitializeAsync is internal.
        
        store.RegisterIndexes(indexProviders);
    }
}
```

I do understand why you made both the `Store` constructor and its `InitializeAsync` methods internal and making them public poses a risk to users using an uninitialized store, so I would understand if you didn't think it worth the change. I would then have to invoke the internal constructor and method using reflection, if I really wanted to.

**Comment by sfmskywalker** [comment]
We'd also have to move a couple of lines from `InitializeAsync` to the constructor, such as:

`_sessionPool = new ObjectPool<Session>(MakeSession, Configuration.SessionPoolSize);`

Otherwise constructing a `Session` will fail.

**Comment by msrcgit** [comment]
I've also wanted to do the same thing, register as a singleton and do a sort of "lazy" loading.

**Comment by wedge206** [comment]
I've also wanted to do the same thing.  Register Store as a singleton, and do a sort of 'lazy' loading.
