### ISSUE TITLE
Indexes are not updated with new values when you store an existing document

### ISSUE THREAD

**Issue by jersiovic** [sebastienros/yessql#19]
Just what the title says

**Comment by sebastienros** [comment]
I don't believe you. Repro steps or unit test. Or the title is very misleading.

**Comment by jersiovic** [comment]
Well I found the problem in the code of this pull request at Orchard 2 https://github.com/OrchardCMS/Orchard2/pull/215 There OpenIdApplicationIndex is not updated when I update values of an OpenIdApplication through Admin UI. Maybe was my fault configuring this YesSQL index. I will check another time how YesSQL expects it to be defined.

**Comment by sebastienros** [comment]
There are so many tests for that, that would be weird it doesn't work. Maybe you forgot to call session.Save() on the updated object.

**Comment by sebastienros** [comment]
It's not automatic like in Orchard 1

**Comment by jersiovic** [comment]
You were right, I forgot to add this lines:
```
            serviceCollection.AddScoped<OpenIdApplicationIndexProvider>();
            serviceCollection.AddScoped<OpenIdTokenIndexProvider>();
```
