### ISSUE TITLE
Distinct Documents from Index

### ISSUE THREAD

**Issue by wedge206** [sebastienros/yessql#202]
The Scenario:

I have a document type that contains a List.
The individual rows from the list are being indexed, so the document can be searched based on the contents of its child list

The Problem:
Some search results will return duplicate documents.  This makes sense because the documents are duplicated in the index.
But what we want/expect is to just return a single instance of a Document, even if it exists multiple times in the Index.

We cannot easily do a Distinct() after the query has executed, because that will break the page sizing.

I don't see any solution or workaround to this problem at the moment.
I feel like a Distinct command or something like it on the binding from the Index to the Document table should be the default behavior.  But that could break other peoples expectation.

**Comment by sebastienros** [comment]
What is the query you are using? 

I could imagine that currently there is an INNER JOIN with the Document table and would return many results. However even if many documents are returned, they should all be the same instance in terms of C# object (can you check)?
Then yes we can probably do a distinct automatically for some queries that join to the document table.

**Comment by wedge206** [comment]
Yes, as far as I can tell it is returning the same instance twice.

Difficult to describe the query.  It's big and it gets assembled based on multiple criteria.

**Comment by sebastienros** [comment]
Maybe write a unit test in a PR that will fail. I assume we already have the domain models necessary to replicate.

**Comment by wedge206** [comment]
Already started doing exactly that
