### ISSUE TITLE
Does Id Generator work across cluster nodes with no collisions?

### ISSUE THREAD

**Issue by ifle** [sebastienros/yessql#205]
Looks like the default id generator implementation does not work across cluster nodes with no collisions.

**Comment by sebastienros** [comment]
How so? Each session, from a node or different ones is holding on a dedicated range of ids, which means there should be no collisions. There are unit tests to ensure that. Unless you found a flaw ...

**Comment by ifle** [comment]
The dedicated range of each node in a cluster based  on max id of the document table, that may cause to collisions
https://github.com/sebastienros/yessql/blob/19ab226263b60d45aa8eb64d9e7d4b489ed8cd93/src/YesSql.Core/Services/DefaultIdGenerator.cs#L60

**Comment by sebastienros** [comment]
For distributed scenarios you need to use UseBlockIdGenerator

https://github.com/sebastienros/yessql/blob/dev/src/YesSql.Core/Services/DbBlockIdGenerator.cs
