### ISSUE TITLE
How to customize MapIndex table name

### ISSUE THREAD

**Issue by HengzheLi** [sebastienros/yessql#236]
Got this when using OrchardCore, and they tell me to ask the question here.

For MapIndex, the table name is "[PartName]Index". This looks like a defaut pattern provided by YesSql during the table creation using CreateMapIndexTable in migration.
So must it has this kind of name for YesSql to find the right table when it does the query operation?
Has a way to customize the table?

**Comment by sebastienros** [comment]
It;s an issue for Orchrad Core ;) answering there
