### ISSUE TITLE
Error commiting changes in two collections

### ISSUE THREAD

**Issue by jersiovic** [sebastienros/yessql#240]
Hello,

I've managed to separate in a diffent Document tokens and authorizations of opeind module. The purpose is to solve the issue mentioned here: https://github.com/OrchardCMS/OrchardCore/issues/6318

For doing that I provide my own stores for those two entities. Also I use this simple wrapper of ISession to avoid having to use have all the code filled with usings for specify everywhere the collection for the operation to yessql. 

```
public class CollectionSession : ISession
    {
        public CollectionSession(string collectionName, ISession session)
        {
            Session = session;
            CollectionName = collectionName;
        }
        public string CollectionName { get; }
        public ISession Session { get; }
        
        public IStore Store => Session.Store;

        public void Cancel()
        {
            using (new NamedCollection(CollectionName))
            {
                Session.Cancel();
            }
        }

        public async Task CommitAsync()
        {
            using (new NamedCollection(CollectionName))
            {
                await Session.CommitAsync();
            }
        }

        public void Delete(object item)
        {
            using (new NamedCollection(CollectionName))
            {
                Session.Delete(item);
            }
        }
        ....
        and so on
```
So the only thing that changes at the original OpenIdTokenStore is this:
```
public OpenIdTokenStore(ISession session)
        {
            _session = new CollectionSession(ModuleCollectionNames.OpenIdCollectionName, session);
        }
```
I ve also override the default Orchard registration of IStore to be able of registering indexes for another collection different from defaul Orchard one. In this way:
```
...
                var indexesPerCollection = sp.GetServices<IIndexProvider>().GroupBy(i => i.CollectionName);
                foreach (var indexes in indexesPerCollection)
                {
                    if (string.IsNullOrWhiteSpace(indexes.Key))
                    {
                        store.RegisterIndexes(indexes);
                    }
                    else
                    {
                        using (new NamedCollection(indexes.Key))
                        {
                            store.RegisterIndexes(indexes);
                        }
                    }
                }
...
```
This is possible cause YesSql IIndexProvider provides a property CollectionName that I initialize with the name of the collection for those indexes that have to work with a different collection.

The point with that is in this way we can use YesSql collections easily and with low impact on any  Orchard module.

Problem is the way Orchard manages ISession and how YesSql expect we store data in collections in separate commits. Because it is difficult to be sure that one commit in Orchard only will change data from one collection.

I fact, this the exception I got when two in the same commit are stored other entities of the open id module in the default collection and the ones I replaced its store:
`System.ArgumentException: 'An item with the same key has already been added. Key: 6'

The reason is IdentityMap has in the same dictionaries ids for both collections.

So, I'm going to provide a PR to allow YesSQL to support in one commit multiple operations on different collections.

**Comment by jersiovic** [comment]
Well, I will provide that PR if this other PR at YesSQL https://github.com/sebastienros/yessql/pull/241 is approved cause I need the feature added to YesSql on that PR.

In fact if that is done I see feasible in a future PR to add a feature that allows to make configurable the collections where entities of a module are stored

**Comment by jersiovic** [comment]
I forgot to mention that currently in Orchard I intialize collections on tenant activation. With the collection names registered on each module:

```
public class AutomaticCollectionDataMigrations : ModularTenantEvents
    {
        private readonly ShellSettings _shellSettings;
        private readonly ILogger _logger;
        private readonly IStore _store;
        private readonly IServiceProvider _serviceProvider;
        private readonly Lazy<IEnumerable<IModuleCollectionNames>> _moduleCollectionNames;

        /// <summary>
        /// Creates a new instance of the <see cref="AutomaticDataMigrations"/>.
        /// </summary>
        /// <param name="serviceProvider">The <see cref="IServiceProvider"/>.</param>
        /// <param name="shellSettings">The <see cref="ShellSettings"/>.</param>
        /// <param name="logger">The <see cref="ILogger"/>.</param>
        public AutomaticCollectionDataMigrations(
            IServiceProvider serviceProvider,
            ShellSettings shellSettings,
            IStore store,
            ILogger<AutomaticDataMigrations> logger)
        {
            _serviceProvider = serviceProvider;
            _shellSettings = shellSettings;
            _moduleCollectionNames = new Lazy<IEnumerable<IModuleCollectionNames>>(() => serviceProvider.GetServices<IModuleCollectionNames>());
            _store = store;
            _logger = logger;
        }

        public Lazy<IEnumerable<IModuleCollectionNames>> ModuleCollectionNames => _moduleCollectionNames;

        /// <inheritdocs />
        public override Task ActivatingAsync()
        {
            if (_shellSettings.State != OrchardCore.Environment.Shell.Models.TenantState.Uninitialized)
            {
                _logger.LogDebug("Executing collection migrations");

                var names = _moduleCollectionNames.Value.SelectMany(m => m.Names).ToList();
                names.ForEach((n) => _store.InitializeCollectionAsync(n));
            }

            return Task.CompletedTask;
        }
    }
```

**Comment by jersiovic** [comment]
@sebastienros  I've changed how things are done, in Orchard side:
Now only thing needed to change at each module where there are documents to store in another collection is to add and register a IModuleCollections class. It is used to define which entities and indexes will be related to different collection than the default one:

````
   public class ModuleCollections : IModuleCollections
    {
        public CollectionEntities[] CollectionEntities =>
            new CollectionEntities[] {
                new CollectionEntities("OpenId", typeof(OpenIdAuthorization), typeof(OpenIdToken), 
                    typeof(OpenIdAuthorizationIndex) , typeof(OpenIdTokenIndex))
            };
    }
````
This is the interface 
```
public interface IModuleCollections
    {
        CollectionEntities[] CollectionEntities { get; }

    }
    public class CollectionEntities
    {
        public CollectionEntities(string name, params Type[] types)
        {
            Name = name;
            Types = types;
        }
        public string Name { get; }
        public Type[] Types { get; }
    }
```
Now I use a at orchard service that provides dictionaries for knowing which collection is used for each class:
````
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using YesSql.Indexes;

namespace KeTePongo.Core.YesSqlCollections
{
    public class YesSQLCollectionNameService
    {
        string[] _collectionNames;
        Dictionary<Type, string> _typeCollection = new Dictionary<Type, string>();
        
        public YesSQLCollectionNameService(IEnumerable<IModuleCollections> moduleCollections)
        {
            foreach (var collection in moduleCollections.SelectMany(m => m.CollectionEntities))
            {
                collection.Types.ToList()
                    .ForEach(type => _typeCollection.Add(type, collection.Name));
            }
            _collectionNames = moduleCollections.SelectMany(m => m.CollectionEntities)
                .Select(e => e.Name).ToArray();
        }
        public string[] GetCollectionNames() => _collectionNames;
        public string GetCollectionNameForType<T>()
        {
            if(!_typeCollection.ContainsKey(typeof(T)))
            {
                return null;
            }
            return _typeCollection[typeof(T)];
        }
        public string GetCollectionNameForType(Type type)
        {
            if (!_typeCollection.ContainsKey(type))
            {
                return null;
            }
            return _typeCollection[type];
        }
    }
}
```
Then I use on my CollectionSession that service to know each entity passed to session on which collection it is related
````
public class CollectionSession : ISession
    {
        private readonly YesSQLCollectionNameService _yesSQLCollectionNameService;
        public CollectionSession(ISession session, YesSQLCollectionNameService yesSQLCollectionNameService)
        {
            Session = session;
            _yesSQLCollectionNameService = yesSQLCollectionNameService;
        }
        public ISession Session { get; }
        
        public IStore Store => Session.Store;

        public void Cancel()
        {
            Session.Cancel();
        }

        public async Task CommitAsync()
        {
            await Session.CommitAsync();
        }

        public void Delete(object item)
        {
            var collectionName = _yesSQLCollectionNameService.GetCollectionNameForType(item.GetType());
            if (collectionName==null)
            {
                Session.Delete(item);
                return;
            }
            using (new NamedCollection(collectionName))
            {
                Session.Delete(item);
            }
        }
....
....
````
With  that only thing that I need is to replace ISession registration with Session per a new one that uses CollectionSession for ISession
````
services.AddScoped(sp =>
            {
                var store = sp.GetService<IStore>();

                if (store == null)
                {
                    return null;
                }
                var collectionNameService = sp.GetService<YesSQLCollectionNameService>();
                if (collectionNameService == null)
                {
                    return null;
                }
                var session = new CollectionSession(store.CreateSession(), collectionNameService);

                var scopedServices = sp.GetServices<IScopedIndexProvider>();

                session.RegisterIndexes(scopedServices.ToArray());

                ShellScope.RegisterBeforeDispose(scope =>
                {
                    return session.CommitAsync();
                });

                return session as ISession;
            });
````
So, at this point, it is not needed to change anything at the data acccess code in any orchard module to be able to change collection where any entity is stored.
Cause in fact with IModuleCollections I can change the collection where is stored any entity in Orchard, not only the ones in the moule. As you can see in my sample I change the collection for OpenIdAuthorization and for OpenIdToken despite that code is not within OpenId module.

Don't you think YesSql could provide directly a Session wrapper similar to SessionCollection instead of having to provide it at Orchard level. Maybe the same can be asked for YesSQLCollectionNameService, but not sure maybe is a good extension point to allow to consumers of YesSql to ptovide its own CollectionNameService.

**Comment by sebastienros** [comment]
I made some progress in sebros/collections.
It's building but no test is passing, there is a table name issue I should find quickly.

I also worked on the Pager and it should be compatible with collections now. Making good progress.
And there shouldn't be any breaking changes in terms of API, if you were not using collections before.
