### ISSUE TITLE
Set table Schema name for SQL Server provider

### ISSUE THREAD

**Issue by michaelnero** [sebastienros/yessql#242]
I've dug through the wiki and the API surface for the SQL Server provider, so I might just be missing it, but is there a way to set the table schema name instead of using the default [dbo] schema? The closest I can find is the TablePrefix feature, but this isn't quite what I'm looking for.

**Comment by sebastienros** [comment]
There is no way AFAIK. Can't it be defined in the connection string, or assigned to the account you are using?

**Comment by michaelnero** [comment]
It can't be defined in the connection string, but I think the default schema can be assigned to a user. If all else fails, I'll go with that approach. Thanks for pointing me in a direction!
