### ISSUE TITLE
Violation of PRIMARY KEY constraint

### ISSUE THREAD

**Issue by eugene-latarevich** [sebastienros/yessql#245]
Hi, 
I got the error "Violation of PRIMARY KEY constraint 'PK__ProductP__3214EC078B57B400'. Cannot insert duplicate key in object 'dbo.ProductPairs_Document'. The duplicate key value is (1619)". 
The situation is two different sessions were trying to add different ProductPairs at the same time but one of them couldn't resolve id and tried to save entity with already existing Id. How can I handle it? I can't understand what to do with it. Should I create one queue for the whole app to manage saving entities?

**Comment by sebastienros** [comment]
> The situation is two different sessions were trying to add different ProductPairs at the same time but one of them couldn't resolve id and tried to save entity with already existing Id

Are you sure they are different session instances? A session is not thread safe, so they can't be share across threads, and that would explain the issue you are seeing. Can you share some code to show me how you are doing this? Or create a unit test that reproduces the issue?

**Comment by eugene-latarevich** [comment]
You can see below repository class. It's scoped class and session is scoped too. Please check extensions below.

`public static IServiceCollection AddYessqlProductPairStore(this IServiceCollection services)
        {
            services.AddScoped<IYessqlDataMigration<ProductPairYessqlStore>, ProductPairMigrations>();
            services.AddScoped<IYessqlIndexProvider<ProductPairYessqlStore>, ProductPairIndexProvider>();

            services.AddSingleton(serviceProvider =>
            {
                var appConfiguration = serviceProvider.GetService<IConfiguration>();
                return YessqlStoreFactory.Create<ProductPairYessqlStore, IYessqlIndexProvider<ProductPairYessqlStore>>(
                    tablePrefix: "ProductPairs_",
                    connectionString: appConfiguration["ConnectionStrings:DefaultConnection"],
                    serviceProvider: serviceProvider);
            });

            return services;
        }

        public static IServiceCollection AddYessqlSessions(this IServiceCollection services)
        {
            services.AddScoped(serviceProvider =>
            {
                var store = serviceProvider.GetService<ProductPairYessqlStore>();
                return (IYessqlSession<ProductPairYessqlStore>)YessqlSessionFactory.Create<ProductPairYessqlStore, YessqlSession<ProductPairYessqlStore>>(store);
            });

            return services;
        }
 `

and repository

`    public class ProductPairRepository : IProductPairRepository
    {
        private readonly ProductPairContext _context;
        private readonly ISession _session;

        public ProductPairRepository(
            ProductPairContext context,
            IYessqlSession<ProductPairYessqlStore> yessqlSession)
        {
            _context = context;
            _session = yessqlSession.Session.;
        }

        public Task AddProductHistoryAsync(IEnumerable<ProductHistory> products) 
            => _context.ProductHistories.AddRangeAsync(products);

        public void AddOrUpdate(YessqlProductPair pair) 
            => _session.Save(pair, true);

        public void AddOrUpdateRange(IEnumerable<YessqlProductPair> pairs) 
            => pairs.ToList().ForEach(pair => AddOrUpdate(pair));

        public Task AddAsync(ArchivedProductPair archivedPair) 
            => _context.ArchivedProductPairs.AddAsync(archivedPair)
            .AsTask();

        public Task AddRangeAsync(IEnumerable<ArchivedProductPair> archivedPairs) 
            => _context.ArchivedProductPairs.AddRangeAsync(archivedPairs);

        public Task<int> CountAsync(
            Expression<Func<ProductByPairIndex, bool>> predicateByUser,
            Expression<Func<InputMarketplaceByProductIndex, bool>> predicateByInputItem,
            Expression<Func<OutputMarketplaceByProductIndex, bool>> predicateByOutputItem)
                => _session
                .Query<YessqlProductPair>()
                .With(predicateByUser)
                .With(predicateByInputItem)
                .With(predicateByOutputItem)
                .CountAsync();

        public Task<int> CountAsync(ProductPairPaginationFilter filter)
            => _session
            .Query<YessqlProductPair>()
            .Where(filter.WhereFilters)
            .CountAsync();

        public Task<YessqlProductPair> FindByIdAsync(int id)
           => _session.GetAsync<YessqlProductPair>(id);

        public Task<IEnumerable<YessqlProductPair>> FindByIdListAsync(int[] ids)
            => _session.GetAsync<YessqlProductPair>(ids);

        public Task<IEnumerable<YessqlProductPair>> ListAsync(ProductPairPaginationFilter filter)
            => _session
            .Query<YessqlProductPair>()
            .WhereWithOrder(filter.WhereFilters, filter.OrderFilters)
            .Skip(filter.Skip)
            .Take(filter.Take)
            .ListAsync();

        public Task<IEnumerable<YessqlProductPair>> ListByUserAsync(Expression<Func<ProductByPairIndex, bool>> predicate)
            => _session
            .Query<YessqlProductPair, ProductByPairIndex>(predicate)
            .ListAsync();

        public Task<IEnumerable<YessqlProductPair>> ListByPairAsync(Expression<Func<ProductByPairIndex, bool>> predicate)
                => _session
                .Query<YessqlProductPair>()
                .With(predicate)
                .ListAsync();

        public Task<IEnumerable<YessqlProductPair>> ListByRepricerRuleAsync(
            Expression<Func<ProductByPairIndex, bool>> predicateByUser,
            Expression<Func<OutputMarketplaceByProductIndex, bool>> predicateByOutputItemId)
                 => _session
                .Query<YessqlProductPair>()
                .With(predicateByUser)
                .With(predicateByOutputItemId)
                .ListAsync();

        public Task<IEnumerable<YessqlProductPair>> ListWithErrorAsync(
            Expression<Func<ProductByPairIndex, bool>> predicateByUser,
            Expression<Func<InputMarketplaceByProductIndex, bool>> predicateByInputItem,
            Expression<Func<OutputMarketplaceByProductIndex, bool>> predicateByOutputItem)
                  => _session
                .Query<YessqlProductPair>()
                .With(predicateByUser)
                .With(predicateByInputItem)
                .With(predicateByOutputItem)
                .ListAsync();

        public void Remove(YessqlProductPair pair) => _session.Delete(pair);

        public void RemoveRange(IEnumerable<YessqlProductPair> pairs) => pairs.ToList().ForEach(pair => Remove(pair));

        public async Task RemoveSearchPairAllAsync(string userId)
        {
            var pairs = await ListByUserAsync(x => x.UserId == userId && x.IsSearchPair == true);
            foreach (var pair in pairs)
            {
                _session.Delete(pair);
            }
        }

        public Task<bool> IsExistAsync(string inputItemId, string outputItemtId)
            => _session
            .Query<YessqlProductPair>()
            .With<ProductByPairIndex>(x => x.IsSearchPair)
            .With<InputMarketplaceByProductIndex>(x => x.ItemId == inputItemId)
            .With<OutputMarketplaceByProductIndex>(x => x.ItemId == outputItemtId)
            .FirstOrDefaultAsync()
            .Bind(productPair => productPair == null
                ? _session
                    .Query<YessqlProductPair>()
                    .With<ProductByPairIndex>(x => !x.IsSearchPair)
                    .With<OutputMarketplaceByProductIndex>(x => x.ItemId == outputItemtId)
                    .FirstOrDefaultAsync()
                : productPair.Result())
            .Bind(productPair => (productPair != null).Result());

        public Task<bool> IsExistWithVariationAsync(string inputItemId, string outputItemtId, string inputVariationValue, string outputVariationValue)
            => _session
            .Query<YessqlProductPair>()
            .With<InputMarketplaceByProductIndex>(x => x.ItemId == inputItemId && x.VariationValue == inputVariationValue)
            .With<OutputMarketplaceByProductIndex>(x => x.ItemId == outputItemtId)
            .FirstOrDefaultAsync()
            .Bind(productPair => (productPair != null).Result());

        public Task<bool> IsExistInHistoryAsync(string inputItemId, string outputItemtId, string type)
            => _context.ProductHistories.AnyAsync(x => x.InputMarketplaceItemId == inputItemId && x.OutputMarketplaceItemId == outputItemtId);

        public Task SaveChangesAsync() => _context.SaveChangesAsync();

        public Task CommitAsync() => _session.CommitAsync();

        public void Dispose()
        {
            _context.Dispose();
            _session.Dispose();
        }
    }`

**Comment by eugene-latarevich** [comment]
Oh! My mistake. I've found that when creates new Job through a factory it creates new service collection with new store. I think it's a problem. I am going to test it. Thank you for your interest.
