### ISSUE TITLE
I get MySqlException using mysql as backend db

### ISSUE THREAD

**Issue by hamdiRuwiss** [sebastienros/yessql#248]
I created a query using orchard core in one controller  : 

          var query = _session.Query<ContentItem, TextFieldIndex>();
            query = query.With<TextFieldIndex>(x => x.ContentType == contentType);
            query = query.With<TextFieldIndex>(x => x.Published);
            query= query.With<TextFieldIndex>(x=>x.Text=="Sale");
            var maxPagedCount = siteSettings.MaxPagedCount;
            if (maxPagedCount > 0 && pager.PageSize > maxPagedCount)
                pager.PageSize = maxPagedCount;
            var routeData = new RouteData();
            var pagerShape = (await New.Pager(pager)).TotalItemCount(maxPagedCount > 0 ? maxPagedCount : await 
             query.CountAsync()).RouteData(routeData);
            var pageOfContentItems = await query.Skip(pager.GetStartIndex()).Take(pager.PageSize).ListAsync();

I get this exception :
MySqlException: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'LIMIT 10 OFFSET 0' at line 1

I use mysql as backend thank you.

**Comment by hishamco** [comment]
@hamdiRuwiss which version of MySQL you are working on, so I may try this?

**Comment by hamdiRuwiss** [comment]
Server version: 10.3.15-MariaDB

**Comment by hamdiRuwiss** [comment]
![image](https://user-images.githubusercontent.com/10530511/85779189-07787400-b72c-11ea-81f4-80ea2ae6c7c0.png)

**Comment by hishamco** [comment]
Unfortunately I don't have MariaDB installed, I have a MySQL 5.7.14, may be the version is matter, one more thing you can do, can you write a unit test against your DB to make it failed. I'm not sure if it's a bug or a limited feature in some versions

**Comment by hamdiRuwiss** [comment]
The same query works when using SQLLite

**Comment by hishamco** [comment]
It's database provider matter, that's why I told you to try to write a unit test to ensure if there's a bug in YesSQL or not

**Comment by sebastienros** [comment]
@hamdiRuwiss there are two ways you could help us here. Simplify your code to the bare minimum to reproduce this issue, so we could translate it in a unit test in yessq, or intercept the SQL that is executed so we can see what went wrong.

**Comment by sebastienros** [comment]
I don't see any OrderBy statement in your code, that might be the issue. Not sure MySQL support pages queries without an order by statement.

**Comment by hishamco** [comment]
> I don't see any OrderBy statement in your code, that might be the issue. Not sure MySQL support pages queries without an order by statement.

Seb, I can verify if this is supported

**Comment by sebastienros** [comment]
Unrelated, but you might want to add a predicate on `ContentField` too on top of `Text=`, it might make the query faster, and also more accurate in case you have another field with the same value.

**Comment by hamdiRuwiss** [comment]
Is there a way to log sql statements generated by YesSql

**Comment by hishamco** [comment]
> Is there a way to view or log sql statements generated by YesSql

Ya, there's a logger in YesSQL AFAIK

**Comment by hamdiRuwiss** [comment]
Please can you point me where to set it up or where to find docs on this

**Comment by hishamco** [comment]
It's a part of `IConfiguration`

**Comment by sebastienros** [comment]
Created a unit test that should match your query, and it worked on all databases we test. Including mysql. https://github.com/sebastienros/yessql/pull/249/files#diff-50c8dfc88150c980068843b43d83c701R2137-R2142

**Comment by hamdiRuwiss** [comment]
Sorry my bad , there is two call to query I didn't notice again i am sorry 
           var pageOfContentItems = await query.Skip(pager.GetStartIndex()).Take(pager.PageSize).ListAsync();
            IEnumerable<ContentItem> model = await query.ListAsync();

**Comment by hamdiRuwiss** [comment]
It worked with SQLLite that is why i didn't noticed when i switched to Mysql

**Comment by hishamco** [comment]
So, is this mean there's no issue at all?!!

**Comment by hamdiRuwiss** [comment]
Yep , thank you for all the help

**Comment by hishamco** [comment]
So, this need to be closed ;)
