### ISSUE TITLE
Querying over collection properties

### ISSUE THREAD

**Issue by hanpera** [sebastienros/yessql#251]
HI,
there is a way to create an index on a property that is a collection inside the document and to query that on some predicates like any(condition)

**Comment by sebastienros** [comment]
Yes, with a map index that would result in one entry for each element in the collection.
You create a Map Index for you document type, and in the lambda you return a collection of index instances.

Here is and example where we have an index for Taxonomies on a Document. For each "tag" (taxonomy term) an index record is created. In a way we project any element from the collection to its own record for querying.
https://github.com/OrchardCMS/OrchardCore/blob/6cddd9f9904ff117ba82587f39fc76f49fac3cc3/src/OrchardCore.Modules/OrchardCore.Taxonomies/Indexing/TaxonomyIndex.cs

You could also create a Reduce Index if you want to group the collection elements across documents, and pre-count them.

**Comment by hanpera** [comment]
Thank you for the answer.
Just another question regarding the queries.
I am not able to build a clause "value IN (value1, value2....)
Usually in EF I was able to write this clause like 

string[] values = new[]{"value1", "value2"...}
var results = query.Where(r => values.Contains(r.Value)

If I write a similar clause with yessql the result is that the variable r is out of scope in session
Thanks in advance

Andrea

**Comment by deanmarcussen** [comment]
You need to use the correct extension method

example 
```
using YesSql.Services;
query.Where(x => x.ContentType.IsIn(values));
```
