### ISSUE TITLE
Optimistic concurrency outside a session - expose Document.Version

### ISSUE THREAD

**Issue by michaelnero** [sebastienros/yessql#252]
YesSql supports optimistic concurrency within a Session, but I'm not sure how to support it outside of one since the Document.Version property isn't exposed anywhere from what I can tell. Is there a way to get the document's Version from one session and provide it when updating an entity in another session? With this, we can support optimistic concurrency in other scenarios, like when a user is editing data on a form.

I could do this work myself by maintaining my own Version on the entity, but this effort seems duplicative.

**Comment by sebastienros** [comment]
I don't think you need to so this. It's transparent. The idea is that if a session writes a document that was modified by another one then a ConcurrencyException is thrown. So when you call Save(o, true) you just need to catch it an retry or display a message. There is a unit test that shows how to do it. And it's optimistic, meaning you never check for it, just fail when a conflict occurs.

**Comment by sebastienros** [comment]
Or maybe I missed your point. How do you handle documents outside of a session?

**Comment by michaelnero** [comment]
Ah, I mean let's say that two users are modifying the same document at the same time through a web form, and then submit the form at about the same time.

What I'd normally do is place the Document's version as a hidden field in the form and post it back with everything else. When handling, I'd do an ```UPDATE <fields> SET <values> WHERE Version = @hidden_field_version```. One of the users will get a 0 row count back because SQL Server will update the row version and and the WHERE clause won't be true for one of them. If the row count is 0, then throw an ConcurrencyException and reload the page with updated data, making the user re-submit the form again.

The way YesSql works now is that just whatever user happens to be last one done editing their form will have their changes applied. There doesn't looks like there's a way to get the documents version and use it in updates.

**Comment by sebastienros** [comment]
What you are describing is exactly what yessql does with the version property "automatically". When you call Save there is an overload with an argument named checkConcurrency. Put it to true and it will do this WHERE clause automatically. Then catch ConcurrencyExcpetion to detect the conflict.

**Comment by michaelnero** [comment]
Sorry, we might be missing something. You're right, YesSql does this automatically _for a document loaded by two users, modified, and saved within a session_, but not when the session's close. However, let's take the following scenario:

User A and User B are editing the _same document_ through a web form.

1. User-A creates a Session-A, loads the document, populates the web form, and then the Session-A is disposed. The request is complete.
2. User-B creates a Session-B, loads the document, populates the web form, and then the Session-C is disposed. The request is complete.
3. There are no open sessions and the document's Version is unknown to User-A and User-B.
4. User-B submits form with Values-A, creates Session-C, updates the documents, saves, and then Session-C is disposed. The request is complete.
5. User-A submits form with Values-B two minutes later, creates Session-D, updates the documents, saves, and then Session-D is disposed. The request is complete.
6. Document contains Value-B (from User-A), but that's only because User-A was the "last one in", but not because this should be the state of the Document.

Note that Session-C and Session-D aren't even open at the same time, and what I'm saying here is that step 5 should fail with a ConcurrencyException, and User-A should get an error to resubmit the form.  But this isn't possible to do currently because I can't manually set the Document's Version and have YesSql use that in the concurrency check.

**Comment by sebastienros** [comment]
Note that you are not supposed to save a document in a session that was not loaded from this session or imported in this session. What would happen is that you would have a duplicate document. So I think you can't technically do what you are describing.

Either you Import() the "cached" values in the new session, or you reload it every time before modifying it. Then the concurrency logic should quick in.

Feel free to create a PR which is adding a unit test if you think it would be better to demonstrate the issue.

**Comment by michaelnero** [comment]
Hello, I submitted a PR that shows the issue you can run into using YesSql in a unit test inside the file SqlServerTests.cs. I also included a small console app that shows how you'd fix this issue with Entity Framework because it exposes and allows you to specify a concurrency token.

**Comment by sebastienros** [comment]
Now I think I understand and agree with your point. Had some doubts already when I woke up, and your example made me realize it fully. I got it once I saw the PersonViewModel that is copying the values of the document.

What I will do is copy the logic that gets/sets the Id of a Document and do the same with Version. This way it will use a property `Version` if it's available on the class, or you can define your own service that will get/set a value based on your own logic (atribute, other name convention, ...).

**Comment by michaelnero** [comment]
I like your idea of copying Version the same way you do with Id properties. This feels pretty clean to me. I'll think on it some more and post back here if I can think of a reason that wouldn't work, but it feels like it should.

By the way, you've done a very nice job overall on this project. :-)

**Comment by sebastienros** [comment]
While I am writing the unit testto check the fix, I realize that you don't need to set the Version, but only to check for it, right?
For instance when you try to save the view model, you just need to check that the document you are updated has the same version as the one you stored in the view model, and you don't need to rely on the ConcurrencyException in this case.

What I am trying to say is that you only need to be able to read the Version value, and not be able to set it. Right?

**Comment by michaelnero** [comment]
Yeah, OK. Just exposing the Version should work in every case I can think of right now. The trickiest timeline would be something like this:

```
            User-A                            User-B
               ↓                                 ↓
     VM.Version = DB.Version           VM.Version = DB.Version
(everything looks good, proceed)   (everything looks good, proceed)
               ↓                                 ↓
             Commit                           Commit            <- One of these will fail due
                                                                   to the concurrency check
                                                                   that already exists in YesSql
```

So I think you're right.

**Comment by sebastienros** [comment]
Both scenarios are supported, either you check the loaded Version property before trying to update the document, or you set the Version property and expect a ConcurrencyException. Ideally you should do both, load the document, check the Version is the same as the ViewModel, then set the Version and Commit, then catch a ConcurrentException if something changed right after you loaded the document.

Can you check the PR? I will merge to dev which will be available on MyGet, where you should be able to test the fix.

**Comment by michaelnero** [comment]
Ah, nice that you're supporting both scenarios. And sure, I'll check out the PR.

**Comment by michaelnero** [comment]
Everything looks good to me! Thanks!
