### ISSUE TITLE
Question: How to chain With clauses on the same Index

### ISSUE THREAD

**Issue by nuno-tiago-reis** [sebastienros/yessql#259]
Hello,

I would like to do the following:

````
var item = await this.DatabaseSession
	.Query<ContentItem, TextFieldIndex>(false)
	.With<TextFieldIndex>(index => index.ContentField == "ID" && index.Text == identifier)
	.With<TextFieldIndex>(index => index.ContentField == "Version" && index.Text == version)
	.FirstOrDefault();
````

The goal here is to find a content item that contains two indices, one with the given ID and one with the given Version. Is there any way to accomplish this? The example I gave above builds the query into something like this:

````
WHERE ([TextFieldIndex].[ContentField] == "ID" AND [TextFieldIndex].[Text] == id) AND ([TextFieldIndex].[Text] == "Version" AND [TextFieldIndex].[Text] == version)
````

Which is impossible to match.

**Comment by sebastienros** [comment]
Shouldn't this work?

```
.With<TextFieldIndex>(index => (index.ContentField == "ID" && index.Text == identifier) || (index.ContentField == "Version" && index.Text == version))
```

**Comment by nuno-tiago-reis** [comment]
That should return values that have either the ID with the given value and/or the Version with the given value.

What I need is for content items that have both of those.

**Comment by sebastienros** [comment]
I assume we need a new operator. What would the SQL look like? I assume it needs to introduce as many "inner join" as we want to.

**Comment by sebastienros** [comment]
I think we should have `With<>` that create a new INNER JOIN, every time, and and `And/Or` that just adds predicates to the current INNER JOIN.

Your query would then become:

```
var item = await this.DatabaseSession
	.Query<ContentItem, TextFieldIndex>(false)
	.With<TextFieldIndex>(index => index.ContentField == "ID" && index.Text == identifier)
	.With<TextFieldIndex>(index => index.ContentField == "Version" && index.Text == version)
	.FirstOrDefault();
``` 

Or also

```
var item = await this.DatabaseSession
	.Query<ContentItem, TextFieldIndex>(false)
	.With<TextFieldIndex>(index => index.ContentField == "ID").And(index => index.Text == identifier)
	.With<TextFieldIndex>(index => index.ContentField == "Version").And(index => index.Text == version)
	.FirstOrDefault();
``` 

Another option would be to be able to pass an alias to the With statement, such that each alias has its own INNER JOIN. That would not break existing queries, as two calls to With would use the same default alias then, and only call to With(alias2, ...) would create a new INNER JOIN.

**Comment by nuno-tiago-reis** [comment]
Your final option sounds good due to the potential code-breaking issues.

````
SELECT
	*
FROM
	[Documents]
INNER JOIN
 	[TextFieldIndex] AS [T1]
ON
	[T1].[DocumentId] = [Documents].[Id] AND [T1].[ContentField] = 'ID' AND [T1].[Text] = <identifier>
INNER JOIN
 	[TextFieldIndex] AS [T2]
ON
	[T2].[DocumentId] = [Documents].[Id] AND [T2].[ContentField] = 'Version' AND [T2].[Text] = <version>
````

What I would do if I was using EntityFramework would be something like this:

````
queryable.Where(item => item.Indices.Any(index => index.ContentField == "ID" && index.Text == identifier) && item.Indices.Any(index => index.ContentField == "Version" && index.Text == version))
````

**Comment by sebastienros** [comment]
I will try to implement this alias solution then. I think it should be easy since this is what I am doing somehow already, but with a value that is the name of the index, to distinguish inner joins on different index tables. So in theory I should just have to introduce and argument to define a custom value instead.
