### ISSUE TITLE
VersionPrefix differs between projects

### ISSUE THREAD

**Issue by ArieGato** [sebastienros/yessql#268]
I was wondering if it is corrrect that some projects have 2.0.0 as version while others have 1.0.0.

YesSql.Abstractions and YesSql.Core are on 2.0.0. The others are on 1.0.0.

I noticed this because I was looking for a new nuget package that will include the changes for the random sort order.

@sebastienros How long before new nuget packages are deployed?

**Comment by sebastienros** [comment]
The discrepancy is due to an older version of yessql.core. Other packages didn't exist.
I could bump everything to 2.0 to fix that.
