### ISSUE TITLE
Wiki says NHibernate is under the hoods but now it is Dapper not NHibernate

### ISSUE THREAD

**Issue by jersiovic** [sebastienros/yessql#28]
Maybe on initial version YesSql was based on NHibernate, but now I haven't find any dependency on it so I imagine documentation wasn't updated reflecting that.

In **Configuring the store** section:

> A store is just a simple relational database instance. It can be any type of SQL database, as long as NHibernate supports it

In **Creating a mapped index** section:

> Properties are  virtual  because it will be mapped in NHibernate to a specific table with the same name as the class.

**Comment by sebastienros** [comment]
Fixed
