### ISSUE TITLE
Join with Linq on Field Other Than DocumentId?

### ISSUE THREAD

**Issue by jeffolmstead** [sebastienros/yessql#282]
This might be OrchardCore specific, but I was not able to find a way via Linq structure to do a join on anything but DocumentId.  For this reason i had to write my own query like this:

```
SELECT T0.DocumentId
FROM ContentItemIndex AS T0
    INNER JOIN ContainedPartIndex AS T1 ON T0.DocumentId = T1.DocumentId
    INNER JOIN ContentPickerFieldIndex AS T2 ON T0.DocumentId = T2.DocumentId
    INNER JOIN ContentItemIndex AS T3 ON T2.SelectedContentItemId = T3.ContentItemId
WHERE T0.ContentType = @ContentType
    AND T1.ListContentItemId = @ListContentItemId
    AND T2.ContentField = @ContentField
    AND T3.Latest = 1
    AND T3.DisplayText LIKE '%' + @Query + '%'
```

That runs fine but isn't strongly typed as it is a string. The line that I cannot currently replicate in Linq is this one:

```
INNER JOIN ContentItemIndex AS T3 ON T2.SelectedContentItemId = T3.ContentItemId
```

This allows me to access the display text for the selected content item(s) so that I can see it if contains a passed in expression. In just Linq, I would have had to utilize two separate queries. 

If this makes sense, the overarching questions is whether or not we can input the fields that two indexes are joined on without resorting to explicitly writing the query out as I have done above.

**Comment by sebastienros** [comment]
Not possible for now. Could be an overload of With<TIndex) that would accept the expression for the join, but it's even harder in your example as you are pointing to another alias (not even T0). So it would be a custom With<TIndex1, TIndex2>(key1, key2, (i1, i2) => predicate1)

Won't happen soon
