### ISSUE TITLE
You released the wrong packages

### ISSUE THREAD

**Issue by Jetski5822** [sebastienros/yessql#285]
@sebastienros Ive been having issues trying your latest Nuget packages; I then debugged the source in Nuget, and found what's in Nuget is not what is in Dev :( - I think you released the wrong packages.

Can you please update them as I really need the latest code on Dev.

**Comment by sebastienros** [comment]
Not sure what I said, but the changes where on dev, not master, so that's why they are not on NuGet, just on myget. I merged it to master now, so it should appear on NuGet very soon.

**Comment by Jetski5822** [comment]
Thanks dude!
