### ISSUE TITLE
[Question] Best Practice for object relationships?

### ISSUE THREAD

**Issue by PoisnFang** [sebastienros/yessql#286]
As an example using the classes below. 
Would I want to serialize and save the list of BlogPosts when I save a blog? Or would it be best to do to what is done in normal SQL and just save the BlogId on the BlogPost and query the list of BlogPosts by BlogId after I pull the Blog object?

```csharp
    public class BlogPost
    {
        public int BlogId { get; set; }
        public int Id { get; set; }

        public string Title { get; set; }

        public string Author { get; set; }

        public string Content { get; set; }

        public DateTime PublishedUtc { get; set; }

        public string[] Tags { get; set; }
    }

    public class Blog
    {
        public int Id { get; set; }
        // should I use [JsonIgnore] here or not?
        public List<BlogPost> Posts { get; set; }
    }
```

**Comment by sebastienros** [comment]
I think you should store Blog Posts in independent documents. In case you get lots of blog posts you won't have to load all of them to display a page or a single one. Optionally you could store the latest ones, or pages or posts but I don't think it would help much.

You can then create an index that contains the BlogId for each BlogPost so you can query posts by blog.
You can also create an index for tags.
And maybe another one for Archives (by year, month, day) as a reduced index, though this can be done with SQL to create count queries.

**Comment by PoisnFang** [comment]
Thats that helps!
