### ISSUE TITLE
[Question] Possible to have auto-incrementing id per class?

### ISSUE THREAD

**Issue by PoisnFang** [sebastienros/yessql#288]
With my SQL Db I was able to have each class be its own table the therefore they would each get their own auto-incrementing id. Is there a way I can do this with YesSql? Currently all the documents are just in one table "Documents" is there any way to break them out?

**Comment by sebastienros** [comment]
You can create "collections" which can hold any object. If you want to create a collection per class you will have to do it whenever you call `Save(collection: "Class1")`.

There is no automatic mechanism to assign specific classes to specific collections.

**Comment by PoisnFang** [comment]
Thanks I will try this out.
