### ISSUE TITLE
Skip() skipped and CountAsync() slow

### ISSUE THREAD

**Issue by jtkech** [sebastienros/yessql#291]
- Is it intended that skip is not taken into account when used before `CountAsync()`

      // Returns the same value as below
      var count = await Session.QueryIndex<AutoroutePartIndex>(i => i.Published)
          .CountAsync();

      // Returns the same value as above
      var count = await Session.QueryIndex<AutoroutePartIndex>(i => i.Published)
          .Skip(5)
          .CountAsync();

- Even if with a little table, is it normal that

      var count1 = await Session.QueryIndex<AutoroutePartIndex>(i => i.Published)
          .CountAsync();

    is much slower than?

      var count2 = (await Session.QueryIndex<AutoroutePartIndex>(i => i.Published)
          .ListAsync())
          .Count();

Note: Working in dev mode so not accurate, and with a little table so not much data over the network when returning all contents in place of only returning the count, but the question remains

**Comment by sebastienros** [comment]
>Is it intended that skip is not taken into account when used before CountAsync()

Yes. It doesn't make sense to skip and count.

> is much slower than?

What database? It shouldn't in theory, so we'd need to know how long it takes to run both queries to see if it comes from the db, from the way the sql is generated, or from the code itself.

**Comment by jtkech** [comment]
> Yes. It doesn't make sense to skip and count.

Okay ;) In fact, because `CountAsync()` was slow, i tried to check if it could be faster with a skip before.

> What database? It shouldn't in theory, so we'd need to know how long it takes to run both queries to see if it comes from the db, from the way the sql is generated, or from the code itself.

I tried it in dev mode, with sqlite, and just with the above code for testing, in the debugger for the 1st query it shows me around 40ms , for the 2nd query 2 or 3 ms, and if i change the calls order it is still the same.

**Comment by jtkech** [comment]
Okay, still in dev mode i didn't see the same difference, just by using the same queries but in a razor view

I did some sql profilings, seems okay on sql server side

I did some benchmarks by using one query (or the other one) in a razor view, and i didn't see a significant difference

So maybe the debugger, i know it is not accurate in dev mode, but the difference was so high.

So i close this issue
