### ISSUE TITLE
Unknown connection type: Microsoft.Data.Sqlite.SqliteConnection

### ISSUE THREAD

**Issue by mariojsnunes** [sebastienros/yessql#292]
Hi,
My OrchardCore tests started breaking in a non-deterministic way after updating from **1.0.0-rc2-15309** to **1.0.0-rc2-15457**.
Throws this error: **Unknown connection type: Microsoft.Data.Sqlite.SqliteConnection**

The YesSql version was updated, might it have something to do with that?
I found a commit related to this: sebastienros/yessql@ed59267

More info on the tests - out of 400 tests, about 5 start breaking. On a re-run, they succeed and others start breaking.

**Comment by sebastienros** [comment]
Probably some concurrency issue. Looking into it ...
