### ISSUE TITLE
[Question] How would I use a string as a primary key?

### ISSUE THREAD

**Issue by PoisnFang** [sebastienros/yessql#294]
I am trying to use YesSql with the build in identity framework of AspNetCore, I noticed that when I try to update a user it creates a new one instead of updating the one that already exists. I am assuming it is because the primary key for a user is a `string` not an `int`

**Comment by sebastienros** [comment]
Here is an implementation of the `UserStore` with YesSql. 
https://github.com/OrchardCMS/OrchardCore/blob/dev/src/OrchardCore/OrchardCore.Users.Core/Services/UserStore.cs

**Comment by PoisnFang** [comment]
@sebastienros I have been looking through that, thanks. However Orchard Core does not implement `IdentityUser` from AspNetCore, they use their own custom User Class. Plus they use 2 IDs. Which would appear to indicate that it is not possible to use a unique string as the primary key for YesSql... I will switch around how I have implement the Identity framework
```csharp
        public int Id { get; set; }
        public string UserId { get; set; }
```

**Comment by sebastienros** [comment]
`public int Id { get; set; }` is the actual identifier in yessql. If you don't have it in a document class it will still be an integer in the database.
`public string UserId { get; set; }` is the logical identifier we use in Orchard. We also add it in a YesSql index so we can query it. I assume you need that too.

**Comment by PoisnFang** [comment]
Right, which the problem with inheriting straight from IdentityUser is that they use the Property name `Id` Thanks I will look into reworking it on my end
https://github.com/dotnet/aspnetcore/blob/master/src/Identity/Extensions.Stores/src/IdentityUser.cs
