### ISSUE TITLE
Can you update the MySqlConnector dependencies?

### ISSUE THREAD

**Issue by CrestApps** [sebastienros/yessql#296]
I am using YesSQL with OrchardCore. Along with YesSQL, I want to to use my own UnitOfWork and Repositories. I am connection to MySQL version 8.0.20 server with a project that is written on the top of .Net 5 framework and EntityFrameworkCore .Net 5 framework as for my ORM. To connect to MySQL, I need  [Pomelo.EntityFrameworkCore.MySql -Version 5.0.0-alpha.2](https://www.nuget.org/packages/Pomelo.EntityFrameworkCore.MySql/5.0.0-alpha.2) which requires [MySQLConnectior >=1.1.0](https://www.nuget.org/packages/MySqlConnector/)

Currently OrchardCore is giving me the following error since the namespaces changed in `MySqlConnector 1.0.0` from `MySql.Data.MySqlClient` to `MySqlConnector`

```
TypeLoadException: Could not load type 'MySql.Data.MySqlClient.MySqlConnection' from assembly 'MySqlConnector, Version=1.0.0.0, Culture=neutral, PublicKeyToken=d33d3e53aa5f8c92'.
```

I am unable to use `Pomelo.EntityFrameworkCore.MySql` for my .Net to connect to MySQL due to this conflict. 

https://github.com/sebastienros/yessql/blob/dev/src/YesSql.Provider.MySql/YesSql.Provider.MySql.csproj#L8

**Comment by CrestApps** [comment]
@sebastienros Thank for your quick fixed! Will we see a new release soon to include this fix and merged in OrchardCore?

**Comment by sebastienros** [comment]
yes, should be quick now

**Comment by CrestApps** [comment]
@sebastienros Perfect! I'll stay tuned here.. I'll test it out once you are ready and I'll report back with any errors.
