### ISSUE TITLE
Support SQL Server 2008

### ISSUE THREAD

**Issue by jersiovic** [sebastienros/yessql#303]
We are migrating our old ERP to Orchard Core, and we need to store and access data at SQL server 2008 servers that is what many of our customer owns.
Problem is we found yes sql doesn't support sql server 2008 sintax for pagination.

I can provide a PR for supporting it with a new SqlServerDialect that inherits from current SqlServerDialect and a few changes at SqlBuilder for allowing dialect to produce nested queries like the one SqlServer needs for pagination.

This other dialect will uncomment current commented lines
```
            // These are not necessary since SQL Server 2008 
            //Methods.Add("day", new TemplateFunction("datepart(day, {0})"));
            //Methods.Add("month", new TemplateFunction("datepart(month, {0})"));
            //Methods.Add("year", new TemplateFunction("datepart(year, {0})"));
```

Is there any other thing you think YesSql is not compatible with Sql Server 2008 that I have to take into account for my PR?
Are you interested on merging a PR like that?

**Comment by sebastienros** [comment]
Please create a new dialect and an extension method to set it on the configuration. I made a change recently that should make it easy, just assign the dialect to the configuration instance.

Please read the latest comments here: https://github.com/sebastienros/yessql/pull/64

**Comment by sebastienros** [comment]
So actually nothing to do but to merge the PR ... working on it

**Comment by jersiovic** [comment]
Mmh I didn't know the syntax used at that PR was supported at sql server 2008.
https://github.com/sebastienros/yessql/pull/64/files#r533631723

RowNum keyword is not supported as far as I know
Most similar thing is ROW_NUMBER() function but is has to be used at select with order as far as I know. So you need to use a subquery

**Comment by jersiovic** [comment]
The pr finally was not accepted cause the complexity required for supporting it will make maintenance hard
