### ISSUE TITLE
CI is running 1.0.0-preview2-003121

### ISSUE THREAD

**Issue by sebastienros** [sebastienros/yessql#31]
Why not 1.0.0 RTM ?

/cc @alexbocharov

**Comment by alexbocharov** [comment]
@sebastienros All right. 

|.NET Core (runtime) Version|DotNet (tooling) Version|
|---|---|
|RC1|1.0.0-rc1-update2 (RC1)|
|RC2|1.0.0-preview1-002702 (Preview 1)|
|1.0.0 (RTM) |1.0.0-preview2-003121 (Preview 2)|
|1.0.1 (RTM)|1.0.0-preview2-003131 (Preview 2)|

**Comment by alexbocharov** [comment]
Еhe final version of the tools is not yet ready [.NET Core CLI](https://github.com/dotnet/cli)
