### ISSUE TITLE
Column with the Guid type is created as a string

### ISSUE THREAD

**Issue by MikeAlhayek** [sebastienros/yessql#311]
I tried to create a database table using a migration with the following method.

```
SchemaBuilder.CreateTable("Vendors", (table) => table
    .Column<Guid>("Id", column => column.PrimaryKey().WithLength(36))
    .Column<string>("Name", (column) => column.WithLength(100).NotNull())
);
```
The above command creates a column of type `Guid` as nvarchar(36) instead of [UniqueIdentifier](https://github.com/sebastienros/yessql/blob/dev/src/YesSql.Provider.SqlServer/SqlServerDialect.cs#L13)

I am able to workaround this problem like this, but think there

```
SchemaBuilder.CreateTable("Vendors", (table) => table
    .Column("Id", DbType.Guid, column => column.PrimaryKey())
    .Column<string>("Name", (column) => column.WithLength(100).NotNull())
);
```

If this is agreed to be a problem, I think the problem is in [this line](https://github.com/sebastienros/yessql/blob/68972b2325c0594f98491fd40e2c77bd75dd3b59/src/YesSql.Core/Sql/Schema/SchemaUtils.cs#L28) which should be changed to `{ typeof(Guid), DbType.Guid}`

**Comment by sebastienros** [comment]
This should be fixed in the latest version. Can you check? There are unit tests too. It's using a string only for the databases that don't support it.

**Comment by CrestApps** [comment]
@sebastienros Yes that indeed fixed the issue. 

I noticed you changed `DbType` to `Type` and you removed the `ISqlDialect Dialect` from the `IStore`. To get the name of the server being used ("MySQL","SqlServer"....) is it valid to do this now?

```
IStore store = serviceProvider.GetRequiredService<IStore>();
string sqlServerName = store.Configuration.SqlDialect.Name;
```
