### ISSUE TITLE
Drop duplicate index

### ISSUE THREAD

**Issue by deanmarcussen** [sebastienros/yessql#322]
I haven't looked into this yet, but recommendations from Azure, is to drop a duplicate index on the `Identifiers` database.

Need to have a look next week and see if there are any recommendations on some prod databases.

![Screenshot 2021-01-02 at 09 13 31](https://user-images.githubusercontent.com/13782679/103454361-09bf1a80-4cdb-11eb-873e-db3470a19728.png)

**Comment by jtkech** [comment]
It's like you created a non clustered index including a column that is a primary key

Is dimension a primary key? If so it is automatically added when you create a non clustered index, even you don't specify it.

**Comment by deanmarcussen** [comment]
I’ve not had a chance to look @jtkech - it’s created by YesSql so not something we’ve done, just there on all our databases

**Comment by jtkech** [comment]
Okay, just found this line of code

https://github.com/sebastienros/yessql/blob/5731eede78d879fb49f458ebd61df1fdafb0010a/src/YesSql.Core/Services/DbBlockIdGenerator.cs#L65

I will dig into it when i will have time

**Comment by jtkech** [comment]
And yes, it is a primary key

https://github.com/sebastienros/yessql/blob/5731eede78d879fb49f458ebd61df1fdafb0010a/src/YesSql.Core/Services/DbBlockIdGenerator.cs#L61

**Comment by jtkech** [comment]
So, we could just remove

https://github.com/sebastienros/yessql/blob/5731eede78d879fb49f458ebd61df1fdafb0010a/src/YesSql.Core/Services/DbBlockIdGenerator.cs#L64-L66

**Comment by deanmarcussen** [comment]
Yeah that looks like it. I assume .PrimaryKey forces an index so no point having a second useless one. Good find

**Comment by jtkech** [comment]
Maybe worth to fix it as commented above because of this new issue on OC https://github.com/OrchardCMS/OrchardCore/issues/8711
