### ISSUE TITLE
Drop Index works only with SQL Server 2016 >

### ISSUE THREAD

**Issue by Skrypt** [sebastienros/yessql#326]
`if exists` here works only in SQL Server 2016 and higher.

``` C#
        public override string GetDropIndexString(string indexName, string tableName)
        {
            return "drop index if exists " + QuoteForColumnName(indexName) + " on " + QuoteForTableName(tableName);
        }
```

**Comment by sebastienros** [comment]
Same for drop tables now, after 2016.
I assume that right now this is the minimum version required. However if you think you can provide a dialect that works for a previous version that's good to, and this can be done outside of yessql too, just inherit from the current one and change the methods that are wrong.

**Comment by Skrypt** [comment]
Yes, I just opened this issue as a reminder of things that doesn't quite work well with SQL Server < 2016. I think we should then probably advise people that OC requires at least SQL Server 2016 to work properly to avoid having people reporting issues with it. Else, I don't think we should invest more time in YesSQL to support old tech. Now and forward only.
