### ISSUE TITLE
Support for Sql CE

### ISSUE THREAD

**Issue by jamesdoran** [sebastienros/yessql#35]
Hi,

I'm having some issues using Sqlite "Doesn't support nested transactions" and "table is locked" errors. Your [Tutorial](https://github.com/sebastienros/yessql/wiki/Tutorial) mentions Sql Server CE 4, so I thought I'd give that a go, but when I try to use it:

`    
ConnectionFactory = new DbConnectionFactory<SqliteConnection>(
    $"Data Source={DatabaseFilename};Cache=Shared", reuseConnection: true),
DocumentStorageFactory = new SqlDocumentStorageFactory(),
    IsolationLevel = IsolationLevel.Serializable
`

I get a "Unknown connection name:sqlceconnection" error. Looking at the code, I've found this in ISqlDialect.cs:

`        public static Dictionary<string, ISqlDialect> SqlDialects { get; } = new Dictionary<string, ISqlDialect>
        {
            {"sqliteconnection", new SqliteDialect()},
            {"sqlconnection", new SqlServerDialect()},
            {"mysqlconnection", new MySqlDialect() }
        };`

Could you add support for Sql Server CE by adding an extra entry to this dictionary?

`{"sqlceconnection", new SqlServerDialect()}`

As it would have the same dialect as Sql Server for the purposes of this library wouldn't it?

Let me know what you think

Thanks,

James

**Comment by sebastienros** [comment]
SqlCe is not supported, because it's not supported on .NET Core. I just pushed an update that supports MySql and verified all SqlIte tests pass. I'd suggest you focus on Sqlite, if you find an issue with it just let me know and I will look into it.

NB: the latest push is using Visual Studio 2017, but the packages are on Nuget if you don't need the source code.

**Comment by jamesdoran** [comment]
Thanks for the quick response Sebastien.

I think my problems _may_ be coming from the fact that I want to have a single Sqlite db file, and then use that file from multiple repository classes.

I have a singleton IStore which is used by 2 repository classes so that I can logically separate the different types of model I'm working with.

Is this a supported use case? 

Thanks,

James

**Comment by sebastienros** [comment]
As long as there is a single instance of `IStore` and two `ISession` are not writing at the same time then it's good. Sqlite doesn't support multiple concurrent write operations, so that not a limitation of yessql it that happens.

**Comment by jamesdoran** [comment]
Is a shared write lock something that could be added to the store to prevent this from happening? Or do all consumers of the yessql library need to manually manage that across sessions?

**Comment by sebastienros** [comment]
Do what you think should be the best for you, and if you hit an issue let me know I will look into how to fix it. I am currently trying to fix something related too.

**Comment by jamesdoran** [comment]
Ok thank you very much. This project is a great idea and I appreciate all the time you're putting into it :)

**Comment by sebastienros** [comment]
YES !!!! I finally managed to get Orchard running with Sqlite, and thanks for motivating me at the exact moment I was about to give up after two days of hard work on MySql ;) I pushed a new version on Nuget, and you can be sure it does work as you would expect concurrently.

Last note, feel free to use as many repositories as you want, but better let them share the same ISession during a request. To do that, just register a scoped session like this: https://github.com/OrchardCMS/Orchard2/blob/master/src/Orchard.Data/ServiceCollectionExtensions.cs#L84

And you don't need to set ReuseConnection for Sqlite anymore.

**Comment by jamesdoran** [comment]
Congratulations :) nice work

Thanks for the code snippet. I'm guessing this is in the context of a Web service. So each user request has a single session object that it can use to do its work during that request. But you'd still need to implement locking (for sqlite) around any writes to synchronise multiple user request threads trying to write at the same time, right? 

My scenario is a fairly simple wpf app for allowing caching of server data locally and the ability to work offline. There are 3 threads:
- user initiated updating of local data
- server to client synchroniser 
- client to server synchroniser

I'll have a play with a simple test harness to see if can reproduce the issue I'm having and raise an issue if I can't get to the bottom of it. If I do find a pattern that works, I might update the quick start documentation if that's ok with you? 

Thanks again
