### ISSUE TITLE
**InvalidCastException** when using inheritance in my models within IndexProvider

### ISSUE THREAD

**Issue by lampersky** [sebastienros/yessql#354]
when trying to register two indexes with models which are using inheritance I'm getting **InvalidCastException**.

here is my test case:
https://github.com/lampersky/yessql/tree/lampersky/index-provider-repro

```
Message: 
    System.InvalidCastException : Unable to cast object of type 'YesSql.Indexes.DescribeContext`1[YesSql.Tests.Models.AnotherPerson]' to type 'YesSql.Indexes.DescribeContext`1[YesSql.Tests.Models.Person]'.
  Stack Trace: 
    IIndexProvider.Describe(IDescriptor context) line 11
    Store.CreateDescriptors(Type target, String collection, IEnumerable`1 indexProviders) line 347
    Store.Describe(Type target, String collection) line 321
    Session.GetDescriptors(Type t, String collection) line 1283
    Session.MapNew(Document document, Object obj, String collection) line 1298
    Session.SaveEntityAsync(Object entity, String collection) line 296
    Session.FlushAsync() line 775
    Session.Dispose() line 650
    CoreTests.InheritedClassTest() line 5276
    --- End of stack trace from previous location ---
```

![image](https://user-images.githubusercontent.com/6403130/110609787-dba00000-818d-11eb-9526-cdbbfa7f4cf8.png)

**Comment by lampersky** [comment]
I think **IsAssignableFrom** (inside CreateDescriptors at Store.cs) cause the problem.
Because of inheritance both **Person** and **AnotherPerson** are assignable from **Person**.

```
        internal IEnumerable<IndexDescriptor> CreateDescriptors(Type target, string collection, IEnumerable<IIndexProvider> indexProviders)
        {
            if (!DescriptorActivators.TryGetValue(target, out var activator))
            {
                activator = MakeDescriptorActivator(target);

                DescriptorActivators = DescriptorActivators.SetItem(target, activator);
            }

            var context = activator();

            foreach (var provider in indexProviders)
            {
                if (provider.ForType().IsAssignableFrom(target) &&
                    String.Equals(collection, provider.CollectionName, StringComparison.OrdinalIgnoreCase))
                {
                    provider.Describe(context);
                }
            }

            return context.Describe(new[] { target }).ToList();
        }
```

**Comment by lampersky** [comment]
I was able to fix this problem with:

![image](https://user-images.githubusercontent.com/6403130/110616880-5ae50200-8195-11eb-9b12-436bd7e1a68d.png)


and now my tests passed :)

![image](https://user-images.githubusercontent.com/6403130/110616798-3ee16080-8195-11eb-826f-2215fd5cec3b.png)

**Comment by deanmarcussen** [comment]
Wouldn't `ForType().Equals` prevent the `PersonAgeIndexProvider` running as well?

So only `AnotherPersonAgeIndexProvider` would run?

Should both run? 

Get a pr together regardless, and then it will be easier to read the tests and understand the behaviour.

**Comment by lampersky** [comment]
IMO those two indices are totally different, they only have some parts in common, that's why I used inheritance to avoid copying and passing common parts, and I expected when querying for data to get only those tecords which type are equals
