### ISSUE TITLE
Indexes with multiple records for one document

### ISSUE THREAD

**Issue by jersiovic** [sebastienros/yessql#355]
### Is your feature request related to a problem? 
For some scenarios we need indexes that have multiple records pointing to a document. An example could be if we define a document called productcatalog that contains all the products of a provider. Having all the products in a document helps us to load fast a complete catalog of a provider which is our most frequent use case.
Problem comes when we want to retrieve provider catalogs that contains a product with certain condition. For that we would need to create a yessql index table where it is stored a record per product in a provider catalog, to be able to search by a product property and know which different catalogs to open. So, the index will have multiple records pointing to the same document.

The work needed for storing data in the index seems expensive, so we now are going to define the index in a yessql map index table, but we are not going to register the index at startup to avoid yessql does the job of keeping the index updated when we store sth.
Instead of that we have a background process that does the job which in the future can be located in another machine). The reason it is not urgent for us this index is coherent with documents, at least we don't need it inmediately and in the same transaction.

### Describe the solution you'd like
It would be nicet Yessql supports to define that kind of indexes and also support to load a document from that kind of index without returning multiple times same document because it found multiple times same documentId on different records.

Furthermore it would be nice YesSql allow us to define if an index has to be sync inmediately after a change on its document, or if it has to be left to the consumer of the library the decission of when it is sync. And for the second case it would be good to have a way of requesting to yessql to sync an index table for a document, passing to that method the Id of the document. It will search for the document id, if it doesn't find it it will act as if the doc was deleted, removing records of that documentId in index table. In other case index tables will be updated with current state of the document.
Another useful thing would be yessql provides a way to patch an index like this new one type. I mean it provides methods to consumers of the library to update specific records of the indexes, cause the consumer code could know on some scenarios exactly which records of the index shoukd be changed and will want to update only records that need to change to make the operation more efficient.

### Describe alternatives you've considered 
For the moment we are going to define a mapindex table not registered at starup for those cases, and all the other operations are going to be done with plain SQL. And for retrieving documents based on one of those indexes we are going to execute a sql toward the index to get the documentIds and then we use yessql to load the document. So, we use two sqls for sth that could be achieved with one with an inner join and a distint if yessql would support these kind of indexes for retrieving documents

**Comment by willnationsdev** [comment]
I also have a use case similar to this. We have dynamic key/value pairs that we must store, and we have downloadable profiles of these records that users can create in the GUI. To present the UI to them, we give them a list of all of the keys that have been created for a given type of record (as its structure may have changed over time). We then give some level of reporting on each key such as when the last time it was inserted by a record or how many records in total have that key. They then select checkboxes of what keys they care about and we fetch all of the records with those keys and return them.

I was going to have a structure in similar to...

Document
Id, Type, Content

Keys (what keys exist? aggregated, unique collection of keys)
Id, KeyName

Structures (what structures of keys exist? unique set of keys per structure ID)
Id, KeyId

RecordKeys (which documents have which structures?)
DocumentId, StructureId

This is in OrchardCore where a specific subset of ContentItems will support this dynamic structuring. In these cases, I'd like to be able to, on ContentItem insert, react to a particular part being present in the ContentItem and, if present, insert multiple rows into the keys table (only if they are unique values though), add a new structure row (only if it is a unique structure), and create a new RecordKeys row. But 2+ rows created through a YesSql Index isn't yet supported.

I'm guessing the best workaround in the meantime is to run separate queries to manage the extra tables (for keys/structures) by directly using the transaction of the ISession with `CurrentTransaction` and performing those operations whenever YesSql does some kind of mutation on the Document table. Not quite sure on the best practice for it though. Is there some kind of YesSql event handler service or do you just inject the operations into the `.Map()` calls or something? Trying to read through the YesSql source to figure it out now...

**Comment by sebastienros** [comment]
> insert multiple rows into the keys table

That's a reduce index. You can pass a custom key property as the discriminator.

> But 2+ rows created through a YesSql Index isn't yet supported

I think it is https://github.com/sebastienros/yessql/blob/1d04a007d893f0287ecc721f087d4f9764f9c90f/test/YesSql.Tests/Indexes/PersonIdentity.cs#L23-L25

**Comment by sebastienros** [comment]
If the answer isn't right I'' spend more time trying to understand 🤷‍♂️

**Comment by willnationsdev** [comment]
@sebastienros Ahh, yes, [I see in the source now](https://github.com/sebastienros/yessql/blob/main/src/YesSql.Abstractions/Indexes/DescribeFor.cs#L20) how you can return multiple records from the map operation.

The documentation wiki gives the impression that the indexes are purely a MapIndex for 1-to-1 relationships and ReduceIndex for Many-to-1 relationships, as it describes here:

> With a map index, one index entry is related to only one object, whereas with a map/reduced, an index entry will represent some information for a set of objects.

So then, to ensure that each generated record is only inserted if its key name is unique, you'd have to use `.Group()` to make the KeyName column become the "Key" for the group and then have `.Reduce()` only return a single record regardless of how many in the `group` input exist. Then, for delete, you'd just check to see if any records in the `map` contain the string for the KeyName column and if not, don't return it.

I think I'm starting to get it. In that case, my use case probably doesn't quite match OP's. Would be good to have the documentation updated to more clearly define the possibilities with the indexes though. If I manage to implement something and verify my personal understanding, maybe I can come back to help with the docs on it.

Thanks!

**Comment by sebastienros** [comment]
I updated it this WE because it was 10 years old, and not relevant at all, still lots of work to do...

**Comment by jersiovic** [comment]
> > insert multiple rows into the keys table
> 
> That's a reduce index. You can pass a custom key property as the discriminator.
> 
> > But 2+ rows created through a YesSql Index isn't yet supported
> 
> I think it is
> 
> https://github.com/sebastienros/yessql/blob/1d04a007d893f0287ecc721f087d4f9764f9c90f/test/YesSql.Tests/Indexes/PersonIdentity.cs#L23-L25

I didn't know it was possible. I close the issue cause it is done then

**Comment by deanmarcussen** [comment]
Also supported with `MapIndex` @jersiovic - not sure from your original post, which you are looking for. See the taxonomy index for an example.

Also of use might be a new method on the mappings `.When(x =>)` which can be used to determine if an index provider should actually perform the mapping.
