### ISSUE TITLE
IsIn<TIndex> Extensions also don't work with collections

### ISSUE THREAD

**Issue by deanmarcussen** [sebastienros/yessql#359]
:(

```
authorization.AuthorizationId.IsNotIn<OpenIdTokenIndex>(
                                         token => token.AuthorizationId,
                                         token => token.Id != 0)
```

throws an exception, because there is no way to pass the `CollectionName` for the inner select, where `OpenIdTokenIndex` is actually `OpenId_OpenIdTokenIndex`

**Comment by sebastienros** [comment]
It's just a matter of an optional argument in the extension method?

**Comment by deanmarcussen** [comment]
Yeah I imagine so, got as far as some failing tests and had to put it down. Will look again tomorrow
