### ISSUE TITLE
Reduce index names too long for MySql

### ISSUE THREAD

**Issue by deanmarcussen** [sebastienros/yessql#361]
Related to https://github.com/OrchardCMS/OrchardCore/pull/8837#issuecomment-804700658

The new code to add the foreign keys for reduce indexes by default is proving too much for MySql (and I assume pgres).

This `MyTable_FK_OpenId_OpenIdAppByLogoutUriIndex_OpenId_Document_DocumentId`

from here https://github.com/sebastienros/yessql/blob/dd587b433c990dc18973957794aad88d868fd5f3/src/YesSql.Core/Sql/SchemaBuilder.cs#L110

(in `CreateReduceIndex`) is producing 70 chars with a small table prefix of `MyTable`

So many ways to fix, and none of them ideal ;)

They need to be unique per database.

But they don't really need to be especially descriptive, as we currently do, because we don't really need to refer back to them afterwards (unlike a table name)

So the dialect could simply truncate it, and tack a guid on the end, or it could be a hash. 

I think MySql handles this by generating it's own hash, when no name is provided. Couldn't say the same for postgres without looking.

Or there are other options like a custom table name convention for OpenId, which just has long class names.

c.f. nhibernate approach 
https://stackoverflow.com/questions/36766848/how-does-hibernate-generate-foreign-key-constraint-names

**Comment by sebastienros** [comment]
I think using a hash of a deterministic name is fine, as we can still find it if necessary. Just keep a standard prefix like FK, IDX, ...
