### ISSUE TITLE
InnoDb, Table without primary key

### ISSUE THREAD

**Issue by TrustMan** [sebastienros/yessql#37]
You have tables without primary key. https://github.com/sebastienros/yessql/blob/master/src/YesSql.Core/Services/Store.cs
It's have method of "InitializeAsync()" which for migration create table without primary key so you can get exceptions. If your Mysql db is using InnoDB.
I propose to determine column of "nextval" as type of "long" and like "primary key".

**Comment by sebastienros** [comment]
This can't be a primary key as multiple records can have the same value. But the composite dimension/nextval could.
