### ISSUE TITLE
Prettify the Data Access APIs

### ISSUE THREAD

**Issue by hishamco** [sebastienros/yessql#39]
Based on the discussion [here](https://github.com/OrchardCMS/Orchard2/issues/638) with @sebastienros in the Orchard CMS repo , there must be changes in both repos to support the suggested APIs, so the developer can simply use YesSQL data provider(s) as the following:

```csharp
public void ConfigureServices(IServiceCollection services)
{
    services.AddDbProvider(options =>
        options.UseSqlServer("Server=.;Database=YesSqlDb;Integrated Security=True"));
    ...
}
```

So, YesSql needs to be configured with a `DbFactory` instance containing a connection string, which you are showing correctly in the example above.

My initial thoughts here is:

- Create the following projects named `YesSql.Provider.InMemory`, `YesSql.Provider.Sqlite`, `YesSql.Provider.SqlServer`, `YesSql.Provider.MySql`, `YesSql.Provider.Postgres`, to support all the data providers which supported by YesSQL, so the user can reference only the one that he interest with (Pluggability)

- Add required unit tests for the suggested APIs

- Provide a web sample as a show case `YesSql.Samples.Web`

@sebastienros please let me know if you have any further suggestion

**Comment by sebastienros** [comment]
`AddDbFactory` in this case? 
Also if a DbFactory accepts a delegated one it should be reflected. For instance https://github.com/sebastienros/yessql/blob/master/src/YesSql.Storage.Cache/CacheDocumentStorageFactory.cs#L15

**Comment by hishamco** [comment]
`AddDbFactory` instead of `AddDbProvider`?

> Also if a DbFactory accepts a delegated one it should be reflected. For instance https://github.com/sebastienros/yessql/blob/master/src/YesSql.Storage.Cache/CacheDocumentStorageFactory.cs#L15

+1, also we can do this by introducing a caching option in the APIs

```csharp
services.AddDbProvider(options =>
        options.UseSqlServer("Server=.;Database=YesSqlDb;Integrated Security=True",
        cached: true));
```
so in this case `newCacheDocumentStorageFactory(new SqlDocumentStorageFactory())` will be created instead of `new SqlDocumentStorageFactory()`
