### ISSUE TITLE
[docs] How to use Schemabuilder

### ISSUE THREAD

**Issue by weirdyang** [sebastienros/yessql#393]
Is there any documentation on how to use the schemabuilder?

I'm trying to understand the orchardcore code and how it works.

For example: https://github.com/OrchardCMS/OrchardCore/blob/32612bef1f017db7961b0fb6ad28a3a61f260b9a/src/OrchardCore.Modules/OrchardCore.ContentFields/Indexing/SQL/Migrations.cs

Why the need for `AlterIndexTable` after calling `CreateMapIndex`? 
From looking at the source [code](https://github.com/sebastienros/yessql/blob/1d04a007d893f0287ecc721f087d4f9764f9c90f/src/YesSql.Core/Sql/SchemaBuilder.cs#L69), isn't `AlterIndexTable` table called already in the `CreateMapIndex` function?

The documentation in the wiki only shows how to use `IndexProvider<>`.

**Comment by hishamco** [comment]
`SchemaBuilder` allow you to apply DDL in your database, in Orchard Core, the `SchemaBuilder` is injected into a `Migration` so you can use a property to manipulate the database schema

**Comment by weirdyang** [comment]
Yes I understand that, but why the double call to `altertableIndex`?

**Comment by hishamco** [comment]
@deanmarcussen any idea?

**Comment by deanmarcussen** [comment]
The `CreateMapIndex` call makes the table, the subsequent `AlterIndexTable` calls create sql key indexes (not related to YesSql indexes) on the columns in the table.

**Comment by weirdyang** [comment]
Thanks @deanmarcussen  and @hishamco
