### ISSUE TITLE
Parser returns terms incorrectly

### ISSUE THREAD

**Issue by awyl** [sebastienros/yessql#403]
In OrchardCore, when you search `text:"some where"`, the `FilterResult` returns `text:some where`.  It changes from a phrase search to a OR search.

Expected: the original terms are returned.

Ref: https://github.com/OrchardCMS/OrchardCore/blob/8ff2453b72b3bcfc3e2c0181b220be5bc720fd96/src/OrchardCore.Modules/OrchardCore.Contents/Controllers/AdminController.cs#L241-L246

**Comment by deanmarcussen** [comment]
Thanks, yes we will just need to track if the Term is quoted or not, when it is parsed
