### ISSUE TITLE
YesSql.ISqlBuilder: how to achive  condition1 and  ( condition2 or condition3 )

### ISSUE THREAD

**Issue by scil** [sebastienros/yessql#414]
how could I write sth like 
```
builder.WhereAnd(condtion1)
builder.WhereAnd( builder.Where(condition2).WhereOr(condition3) )
```

**Comment by deanmarcussen** [comment]
it depends on what sql you're actually trying to achieve, but look at the query options and keep building.

possible example: 

```
var query = _session.Query<Foo,FooIndex>();
query.All(x => query.With...)

or
query.Any(x => query.With...)
```

**Comment by scil** [comment]
Thank you.

right now i'm withing with tables except table `Docuemnt`.   

so I can not use `_session.Query`

I have to use `_dbConnectionAccessor` and `sqlBuilder`.

Maye i should write the sql clause mannuly, just like  [left join](https://github.com/sebastienros/yessql/issues/408#issuecomment-986404068)

**Comment by scil** [comment]
skip `WhereOR`, just write `OR` mannuly and it worked

```
sqlBuilder.WhereAnd(
                                $" ( a.{dialect.QuoteForColumnName(nameof(CommentRecord.AuditStatus))} = @status" +
                                $" OR a2.{dialect.QuoteForColumnName(nameof(CommentRecord.AuditStatus))} = @status ) ");
```
