### ISSUE TITLE
Question related to TemporaryFolder

### ISSUE THREAD

**Issue by intellimedhu** [sebastienros/yessql#451]
I like the way you are using `TemporaryFolder` for testing. I've tried to implement it and run my own tests in VS, but I have an exception when it tries to delete the folder:

`System.IO.IOException : The process cannot access the file '... yessql.db' because it is being used by another process`

https://github.com/sebastienros/yessql/blob/0b8dd422407b5216882d2dc990d74ab29c4e56cd/test/YesSql.Tests/TemporaryFolder.cs#L24

It may be related to how the `Store` is "disposing" (or not, because the [method is empty](https://github.com/sebastienros/yessql/blob/0b8dd422407b5216882d2dc990d74ab29c4e56cd/src/YesSql.Core/Store.cs#L246)).

Can you reproduce this error? Any idea how to solve it?

**Comment by hishamco** [comment]
Be sure the file unlocked before delete the temp folder

**Comment by intellimedhu** [comment]
`SqliteConnection.ClearAllPools();` was missing.
