### ISSUE TITLE
SQL Indexes names should be prefixed by schema

### ISSUE THREAD

**Issue by sebastienros** [sebastienros/yessql#492]
They are already prefixed with the TablePrefix, they should also use the schema name since they are defined across schemas.

https://github.com/sebastienros/yessql/blob/c0771eb555c67bf419859016cb3563a3540fe7c7/src/YesSql.Core/Sql/Schema/AlterTableCommand.cs#L55-L75

**Comment by hishamco** [comment]
Shall we use dot notation between schema & table prefix?

**Comment by hishamco** [comment]
Is it resolved?
