### ISSUE TITLE
Have you considered using of XML columns in SQL Server for document storing?

### ISSUE THREAD

**Issue by xperiandri** [sebastienros/yessql#51]
There are more options to manipulate with such type of column that a simple `VARCHAR`

**Comment by sebastienros** [comment]
I have not considered it intentionally. I want something that can work with any RDBMS.
I agree this would be much better if we could provide custom implementations for each database.

**Comment by xperiandri** [comment]
Are there any unique features in other supported DBMSs like XML columns in SQL Server?

**Comment by sebastienros** [comment]
yes, postresql has json support, btw SQl Server also supports json

**Comment by xperiandri** [comment]
Looks cool
https://docs.microsoft.com/en-us/sql/relational-databases/json/json-data-sql-server
So computed indexes can be made by JSON data.
And id can be modified on insert
