### ISSUE TITLE
Upgrade Microsoft.Data.Sqlite to v8.0.0

### ISSUE THREAD

**Issue by Piedone** [sebastienros/yessql#510]
The v.8.0.0 of `Microsoft.Data.Sqlite` is out. That [depends on](https://www.nuget.org/packages/Microsoft.Data.Sqlite/8.0.0#dependencies-body-tab) >=2.1.6 of [`SQLitePCLRaw.bundle_e_sqlite3`](https://github.com/ericsink/SQLitePCL.raw). This in turn is notable because it fixes an issue where you get the below build warnings when building a project using it under the .NET 8 SDK (see https://github.com/ericsink/SQLitePCL.raw/issues/543).

> Found version-specific or distribution-specific runtime identifier(s): alpine-arm, alpine-arm64, alpine-x64. Affected libraries: SQLitePCLRaw.lib.e_sqlite3. In .NET 8.0 and higher, assets for version-specific and distribution-specific runtime identifiers will not be found by default. See https://aka.ms/dotnet/rid-usage for details.

**Comment by MikeAlhayek** [comment]
@Piedone if you are planning to submit a PR, please target release/4.0 instead of main.

**Comment by sebastienros** [comment]
but this could also be released today on 3.x and merged into release/4.0, if it's blocking it doesn't have to wait and it is not a breaking change

**Comment by MikeAlhayek** [comment]
@sebastienros yes sure if you want to depend on .net 8

**Comment by sebastienros** [comment]
@MikeAlhayek Sqlite 8.0 targets .NET Standard 2.0 (check on nuget, I did too). The issue might appear with the SDK 8.0, but the package doesn't target net8.0 "only". It targets all TFMs. However what Zoltan says is that if the application targets net8.0 (or if they use the latest sdk, I am not sure) there is a warning.

If we bump to sqlite 8.0, we can still target net6.0 specifically (and version above as a result) without breaking anything.
