### ISSUE TITLE
PostgreSQL - use identity instead of serial

### ISSUE THREAD

**Issue by MikeKry** [sebastienros/yessql#517]
Hi,

according to docs, serial primary key should not be used anymore. Maybe it would be worth to apply this change to postgresql dialect
https://wiki.postgresql.org/wiki/Don%27t_Do_This#Don.27t_use_serial

**Comment by hishamco** [comment]
Could you please submit a PR?

**Comment by neglectedvalue** [comment]
Hello folks, I've also noticed usage of 'serial' so I've created a PR https://github.com/sebastienros/yessql/pull/551 , could you please take a look on it ?
