### ISSUE TITLE
BatchCommand.DefaultBuilderCapacity is not used

### ISSUE THREAD

**Issue by PiemP** [sebastienros/yessql#572]
Good day to everyone.

Today I have initialized a new OrchardCore site and I have see this line in the logging file: 

```
YesSql|The default capacity of the BatchCommand StringBuilder 10240 might not be sufficient. It can be increased with BatchCommand.DefaultBuilderCapacity to at least 41448
```

I have search about it but I don't find any information. This should be worry me?

Thank you

**Comment by hishamco** [comment]
https://github.com/sebastienros/yessql/blob/01fea28df4f091bd8c0904c6bf514c2ad7fdd663/src/YesSql.Core/Commands/BatchCommand.cs#L61

**Comment by sebastienros** [comment]
It's actually a useless warning because the `DefaultBuilderCapacity` constant is not even used. I believe it was intended for a `StringBuilder` but the current logic is just concatenating all the queries into a single one (probably using an SB though).

**Comment by PiemP** [comment]
Thank you guys, 

I can close this question or you prefer that I leave it open?

**Comment by sebastienros** [comment]
I renamed it so we can leave it opened

**Comment by hishamco** [comment]
Shall we remove this warning Seb?

**Comment by Piedone** [comment]
This was used when adding it in https://github.com/sebastienros/yessql/pull/316 but not anymore. Seems like a trivial fix, so submitted https://github.com/sebastienros/yessql/pull/584.
