### ISSUE TITLE
What methods are allowed when using Linq?

### ISSUE THREAD

**Issue by weirdyang** [sebastienros/yessql#576]
I noticed I can not using `ToLower()` and `.Contains`, what else should I avoid?

**Comment by hishamco** [comment]
YesSQL has some of LINQ like methods, but not all you can check the source code to know which are supported

**Comment by weirdyang** [comment]
> YesSQL has some of LINQ like methods, but not all you can check the source code to know which are supported
> 
> https://github.com/sebastienros/yessql/blob/main/src/YesSql.Abstractions/IQuery.cs

Sorry I meant the operators and methods I can use within the Linq methods, like those I've shared in my OP, eg. String.ToLower(), using String.ToLower() throws an exception.

**Comment by hishamco** [comment]
`ToLower() and `Contains()` are string methods how they are related? Where did you call them?

**Comment by weirdyang** [comment]
Please see the op, I said within the linq extensions, eg Where(x => x.Name.ToLower() == "test")

**Comment by MikeAlhayek** [comment]
Here is a list

https://github.com/sebastienros/yessql/blob/1ff3fd3894a6b591de8c7f9ee3301eb51ccf8972/src/YesSql.Core/Services/DefaultQuery.cs#L137

- .StartsWith("") and .StartsWith('')
- .EndsWith("") and .EndsWith('')
- .Contains("") and .Contains('')
- .Concat([""]) .Concat(""), .Concat("", ""), .Concat("", "", ""), and .Concat("","","","")
- .Min(), .Max(), .Count(), .Average(), .Sum()
- IsLike("") 
- IsNotLike("")
- .NotContains("")
- IsIn([])
- IsNotIn([])

**Comment by weirdyang** [comment]
> Here is a list
> 
> https://github.com/sebastienros/yessql/blob/1ff3fd3894a6b591de8c7f9ee3301eb51ccf8972/src/YesSql.Core/Services/DefaultQuery.cs#L137
> 
> * .StartsWith("") and .StartsWith('')
> * .EndsWith("") and .EndsWith('')
> * .Contains("") and .Contains('')
> * .Concat([""]) .Concat(""), .Concat("", ""), .Concat("", "", ""), and .Concat("","","","")
> * .Min(), .Max(), .Count(), .Average(), .Sum()
> * IsLike("")
> * IsNotLike("")
> * .NotContains("")
> * IsIn([])
> * IsNotIn([])

thanks!!

**Comment by hishamco** [comment]
DefaultQuery implements `IQuery` which I refer to last week :)
