### ISSUE TITLE
LINQ instead of manual query building

### ISSUE THREAD

**Issue by xperiandri** [sebastienros/yessql#66]
Why don't you use LINQ and EF providers to generate SQL but do that manually?

**Comment by sebastienros** [comment]
It already supports LINQ to do any SELECT query. I don't see what EF has to do with it.
To store document and indices the SQL is done manually as the model is dynamic, and EF would not support that easily (I tried with the help of the EF team in the early days of YesSql core).

**Comment by xperiandri** [comment]
Not EF, but EF database providers to generate SQL from LINQ.
But if there is an ability to specify index with `IndexAttribute` then there must be an API to create it manually too. Isn't it?
