### ISSUE TITLE
YesSQL need to be upgraded to Core 2.0 to be usable in Orchard at Core 2.0

### ISSUE THREAD

**Issue by xperiandri** [sebastienros/yessql#68]
Because of dependency at `System.Data.SqlClient` lower than 4.4.0 Orchard ported to Core 2.0 when deployed to Azure WebApp fails to configure database.
See https://github.com/Azure/app-service-announcements-discussions/issues/9

**Comment by sebastienros** [comment]
Fixed, thanks
