### ISSUE TITLE
Native free C# Db with graph/object support LiteDB fully C# & free!

### ISSUE THREAD

**Issue by weedkiller** [sebastienros/yessql#80]
Hi, this lib is `C#  native DB 300kb Dll` with ~2600 followers, very **popular and free** [LiteDB fully C#](https://github.com/mbdavid/LiteDB), supported by @mbdavid

**Can you please include LiteDB as a YesSql Container as well.** It would give us the document functions from YesSql on top of LiteDB, while yesSql can do complex indices, graphs etc - cross platform.

In your samples can you please share some info on `joins `for e.g. when an `Customer PersonVM` is needed from `ASP Identity` user table and `Orders` total table

How to get subscribe/change notifications from cache, and YesSql. For e.g. force user log out broadcast while user is logged in a session (if his payment expired)

thanks

**Comment by sebastienros** [comment]
I am very sorry, I don't understand anything in this issue. Can you try to rephrase what you are looking for?

**Comment by weedkiller** [comment]
I am asking that you support LiteDB as the backend for YesSql (since its free, widely used, & native C# core).

This removes many of the restrictions that traditional RDB's have on YesSql, like in the other case where someone was also complaining about complex indices, complex joins.

In the end, this give YesSql the full range of a document store by using LiteDB as the provider.

**Comment by sebastienros** [comment]
The store for YesSql needs to be support SQL. And I don't think this is the case for LiteDB.

**Comment by weedkiller** [comment]
You dont need SQL, you can directly persist C# objects, _I think once they have the interface_

thanks for looking into it. I will close it out, but interacting with an object directly gives you so much more freedom and functionality

**Comment by sebastienros** [comment]
> You dont need SQL

LiteDB might not need it, but YesSql depends on it, hence the `Sql` part in the name ;)
