### ISSUE TITLE
When updating a document entry, existing unmapped data gets removed

### ISSUE THREAD

**Issue by mylemans** [sebastienros/yessql#9]
Scenario:

You have a document with field A and B.

I then save away a document.

Then I modify my 'model' so that it has field A and C.

I retrieve the existing document, A will be filled, C will be empty, and then save it away again as-is (as I received it in the first place)

Result: It'll store A and an empty C field, but the contents of the B field will be have been removed.

Imho, there should be a way to make it so that existing 'unmapped' data can be kept when updating an entry. Either by default or optionally.

We're actually considering using this for a 'cloud' storage solution (of 'data', not files) but that would require YesSql to be able to update a record with new data without removing the unmapped data.

For example: one of the 'users' could be running on an 'old' model, without this ability any 'old model' user would be able to 'remove' unmapped field data. 

It would kinda beat the cloud concept if we'd have to update all 'clients' at the same time to prevent this kind of loss.

AimOrchard here btw ;)

**Comment by sebastienros** [comment]
I think it should work with the new version. The json document is untouched.
